#! /usr/bin/env bash
BASEDIR=$(dirname $0); cd $BASEDIR

. ../env-vars

_require_var YT_DLP_AUDIO_OUTPUT_FOLDER
_require_var DOWNLOADS_HOME

__usage_page() {
    echo "Fetch audio on MP3 format."
    echo ;
    echo "Usage: $(basename $0) [<option>]*"
    echo "Option:"
    echo "    -u <URL>:      Resource URL"
    echo "    -s <index>:    Playlist start index"
    echo "    -l <location>: File for a list of URLs"
    echo "    -p:            Pack MP3 files into a ZIP file and delete the MP3's"
    echo "    -m:            Move all ZIP files to 'DOWLOADS_HOME' location"
    echo "    -h:            Displays this help message"
    exit 0
}

_pack_audios() {
    cd "$YT_DLP_AUDIO_OUTPUT_FOLDER"

    if [ -n "$(find . -name '*.mp3')" ]; then
        local _last_zip_file="$(ls | grep .*\\.zip | sort -V | tail -1)"
        local _audio_part="audio"
        local _extension_part=".zip"
        local _audio_length=${#_audio_part}
        local _extension_length=${#_extension_part}
        local _counter=0

        if [ -n "$_last_zip_file" ]; then
            _last_zip_file_length=${#_last_zip_file}
            _counter=${_last_zip_file:$_audio_length:$(($_last_zip_file_length-$_audio_length-$_extension_length))}
            _counter=$(($_counter+1))
        fi

        local _package=$_audio_part$_counter$_extension_part

        zip -r $_package *.mp3
        echo "ZIP generated: $_package"

        rm -f *.mp3

        echo "MP3 files were cleaned"
    else
        echo "MP3 files not found"
    fi

    _completed
}

_move_outputs() {
    if [ -n "$(find $YT_DLP_AUDIO_OUTPUT_FOLDER -name '*.zip')" ]; then
        rsync -av --remove-source-files $YT_DLP_AUDIO_OUTPUT_FOLDER/*.zip "$DOWNLOADS_HOME"
        echo "ZIP files moved to: $DOWNLOADS_HOME"
    else
        echo "ZIP files not found"
    fi

    _completed
}

_download_audio() {
    local _url=${1:-}

    if [ $_playlist_flag -eq 1 ]; then
        yt-dlp -x --audio-format mp3 --audio-quality 4 --playlist-start $_playlist_start --rm-cache-dir "$_url"
    else
        yt-dlp -x --audio-format mp3 --audio-quality 4 --rm-cache-dir "$_url"
    fi

    echo ;
    [ $? -eq 0 ] && echo "Downloaded: $_url" >&2 || echo "Unable to download: $_url" >&2
}

_download_resource() {
    cd "$YT_DLP_AUDIO_OUTPUT_FOLDER"

    if [ -z "$_list_file" ]; then
        _download_audio "$_src_url"
    else
        _playlist_flag=0

        while IFS= read -r line || [ -n "$line" ]; do
            _download_audio "$line"
        done < $_list_file

        cat $_list_file
        rm -f $_list_file
    fi
}

_playlist_flag=0

while getopts "u:s:l:pmh" opt; do
    case "$opt" in
        u)
            _src_url="$OPTARG"
            ;;
        s)
            _playlist_start=${OPTARG:-1}
            _playlist_flag=1
            ;;
        l)
            _list_file="$OPTARG"
            ;;
        p)
            _pack_audios
            ;;
        m)
            _move_outputs
            ;;
        h)
            __usage_page
            ;;
    esac
done

_download_resource

_completed
