#! /usr/bin/env bash
BASEDIR=$(dirname $0); cd $BASEDIR

. ../env-vars

_require_var YT_DLP_VIDEO_OUTPUT_FOLDER
_require_var YT_DLP_COOKIES_DB_PARENT
_require_var SESSION_TEMP_DIR
_require_var HOSTS_DB_FILE

__usage_page() {
    echo "Fetch video on MP4 format."
    echo ;
    echo "Usage: $(basename $0) [<option>]*"
    echo "Option:"
    echo "    -u <URL>:          Resource URL"
    echo "    -a:                Get available formats for the video"
    echo "    -r <resolution>:   Video resolution, numeric"
    echo "    -c:                Attach cookies to request"
    echo "    -l <location>:     File for a list of URLs"
    echo "    -p:                Pack MP4 files into a ZIP file and delete MP4 files"
    echo "    -m:                Move all ZIP files to 'DOWNLOADS_HOME' location"
    echo "    -h:                Displays this help message"
    exit 0
}

. ./.libs/url-source

_hosts_db_file="$HOSTS_DB_FILE"


_pack_videos() {
    cd "$YT_DLP_VIDEO_OUTPUT_FOLDER"

    local _mp4_files=$(find . -name '*.mp4' -type f)

    if [ -n "$_mp4_files" ]; then
        local _counter=0
        
        while IFS= read -r _zip_file; do
            if [ -n "$_zip_file" ]; then
                local _basename_zip=$(basename "$_zip_file")
                if [[ "$_basename_zip" =~ ^video([0-9]+)\.zip$ ]]; then
                    local _num="${BASH_REMATCH[1]}"
                    if [ "$_num" -ge "$_counter" ]; then
                        _counter=$(( _num + 1 ))
                    fi
                fi
            fi
        done < <(find . -name 'video*.zip' -type f | sort -V)

        local _package="video${_counter}.zip"

        zip -r $_package . -i *.mp4
        echo "ZIP generated '$_package' in: $YT_DLP_VIDEO_OUTPUT_FOLDER"

        read -p "Remove packed MP4 files? y/n> " _yesno
        case $_yesno in
            [Yy]*)
                find . -name '*.mp4' -type f -delete
                find . -type d -empty -delete
                echo "MP4 files were cleaned"
            ;;
        esac
    else
        echo "MP4 files not found in: $YT_DLP_VIDEO_OUTPUT_FOLDER"
    fi

    _completed
}

_move_outputs() {
    cd "$YT_DLP_VIDEO_OUTPUT_FOLDER"

    if [ -n "$(find . -name '*.zip')" ]; then
        rsync -av --remove-source-files $YT_DLP_VIDEO_OUTPUT_FOLDER/*.zip "$DOWNLOADS_HOME"
        echo "ZIP files moved to: $DOWNLOADS_HOME"
    else
        echo "ZIP files not found in: $YT_DLP_VIDEO_OUTPUT_FOLDER"
    fi

    _completed
}

_create_cookies() {
    local _url=${1:-}
    local _host=$( _get_cookies_host "$_url" )
    local _sql_file=$( ls -t $YT_DLP_COOKIES_DB_PARENT/*/cookies.sqlite | head -1 )

    if [ -z "$_sql_file" ]; then
        echo "SQLite file not found" >&2
        _stopped
    fi

    if [ ! -r "$_sql_file" ]; then
        echo "File $_sql_file is not readable" >&2
        _stopped
    fi

    local _tmp_file=$( mktemp "$SESSION_TEMP_DIR/cookies.sqlite.XXXXXXXXXX" )
    cat "$_sql_file" >> $_tmp_file

    local _sql="select host as domain,"
    _sql+=" case substr(host,1,1)='.' when 0 then 'false' else 'true' end as subdomains,"
    _sql+=" path,"
    _sql+=" case isSecure when 0 then 'false' else 'true' end as secure,"
    _sql+=" expiry,"
    _sql+=" name,"
    _sql+=" value"
    _sql+=" from moz_cookies mc"
    _sql+=" where mc.host = '$_host';"

    sqlite3 -json $_tmp_file "$_sql" > "$SESSION_TEMP_DIR/json-cookies.json"

    rm -f $_tmp_file

    $(command -v python3 || command -v python) "$SCRIPTS_HOME/misc/.py/netscape_cookies.py" \
        -j "$SESSION_TEMP_DIR/json-cookies.json" \
        -n "$SESSION_TEMP_DIR/netscape-cookies.txt"

    rm -f "$SESSION_TEMP_DIR/json-cookies.json"

    echo "$SESSION_TEMP_DIR/netscape-cookies.txt"
}

_select_resolution() {
    echo >&2
    echo "Which resolution do you want?" >&2
    echo "1) SD (480p)" >&2
    echo "2) HD (720p) (default)" >&2
    echo "3) Full HD (1080p)" >&2
    read -p "resolution-index> " _resolution_index

    if [ -z "$_resolution_index" ]; then
        _resolution_index=2
    fi

    case "$_resolution_index" in
        1)
            echo "480"
            ;;
        2)
            echo "720"
            ;;
        3)
            echo "1080"
            ;;
        *)
            echo "Invalid resolution option: $_resolution_index" >&2
            _stopped
            ;;
    esac
}

_available_formats() {
    local _url=${1:-}
    local _cookies=${2:-}

    if [ -f "$_cookies" ]; then
        yt-dlp --list-formats --cookies "$_cookies" --rm-cache-dir "$_url"
    else
        yt-dlp --list-formats --rm-cache-dir "$_url"
    fi

    rm -f "$_cookies"
}

_download_video() {
    local _url=${1:-}
    local _resolution=${2:-}
    local _cookies=${3:-}
    local _source=$( _get_source "$_url" )

    cd "$YT_DLP_VIDEO_OUTPUT_FOLDER/$_source"

    if [ -f "$_cookies" ]; then
        yt-dlp -S "res:$_resolution" --recode-video "mp4" \
            --cookies "$_cookies" \
            --restrict-filenames --windows-filenames \
            --rm-cache-dir --no-overwrites \
            -o "%(uploader)s/%(title)s.%(ext)s" "$_url"
    else
        yt-dlp -S "res:$_resolution" --recode-video "mp4" \
            --restrict-filenames --windows-filenames \
            --rm-cache-dir --no-overwrites \
            -o "%(uploader)s/%(title)s.%(ext)s" "$_url"
    fi

    if [ $? -eq 0 ]; then
        local _recent_file=$( fd -t f . -x stat -c "%y %n" {} \; | sort -r | head -1 )

        echo >&2
        echo "Downloaded: $_url" >&2
        echo "Output file: $_recent_file" >&2
    else
        echo >&2
        echo "Unable to download: $_url" >&2
    fi
}

_download_resource() {
    local _url=${1:-}
    local _list=${2:-}
    local _res=${3:-}
    local _cookies=${4:-}

    if [ -z "$_res" ]; then
        _res=$( _select_resolution )
    fi

    if [ -z "$_list" ]; then
        _download_video "$_url" "$_res" "$_cookies"
    else
        while IFS= read -r line || [ -n "$line" ]; do
            _download_video "$line" "$_res" "$_cookies"
        done < $_list

        echo ;
        cat $_list
        rm -f $_list
    fi

    rm -f "$_cookies"
}

_src_url=""
_available_flag=0
_resolution=""
_cookies_flag=0
_cookies_file=""
_list_file=""

while getopts "u:ar:cl:pmh" opt; do
    case "$opt" in
        u)
            _src_url="$OPTARG"
            ;;
        a)
            _available_flag=1
            ;;
        r)
            _resolution="$OPTARG"
            ;;
        c)
            _cookies_flag=1
            ;;
        l)
            _list_file="$OPTARG"
            ;;
        p)
            _pack_videos
            ;;
        m)
            _move_outputs
            ;;
        h)
            __usage_page
            ;;
    esac
done

if [ $_cookies_flag -eq 1 ]; then
    _cookies_file=$( _create_cookies "$_src_url" )
fi

if [ $_available_flag -eq 1 ]; then
    _available_formats "$_src_url" "$_cookies_file"

    _completed
fi

echo ;
echo "Tip: If URL has '&' params, remove if don't needed or use any of the alternatives:"
echo "  quote: $0 -u '...&<param>=<value>'"
echo "  escape: $0 -u ...\\&<param>=<value>"

_download_resource "$_src_url" "$_list_file" "$_resolution" "$_cookies_file"

_completed
