#! /usr/bin/env bash
BASEDIR=$(dirname $0); cd $BASEDIR

. ../env-vars

_require_var YT_DLP_AUDIO_OUTPUT_FOLDER
_require_var DOWNLOADS_HOME

__usage_page() {
    echo "Fetch audio on MP3 format."
    echo ;
    echo "Usage: $(basename $0) [<option>]*"
    echo "Option:"
    echo "    -u <URL>:      Resource URL"
    echo "    -s <source>:   Source site, default: 'YouTube'"
    echo "    -i <index>:    Playlist start index"
    echo "    -l <location>: File for a list of URLs"
    echo "    -p:            Pack MP3 files into a ZIP file and delete MP3 files"
    echo "    -m:            Move all ZIP files to 'DOWLOADS_HOME' location"
    echo "    -h:            Displays this help message"
    exit 0
}

_pack_audios() {
    cd "$YT_DLP_AUDIO_OUTPUT_FOLDER"

    local _mp3_files=$(find . -name '*.mp3' -type f)

    if [ -n "$_mp3_files" ]; then
        local _counter=0
        
        while IFS= read -r _zip_file; do
            if [ -n "$_zip_file" ]; then
                local _basename_zip=$(basename "$_zip_file")
                if [[ "$_basename_zip" =~ ^audio([0-9]+)\.zip$ ]]; then
                    local _num="${BASH_REMATCH[1]}"
                    if [ "$_num" -ge "$_counter" ]; then
                        _counter=$(( _num + 1 ))
                    fi
                fi
            fi
        done < <(find . -name 'audio*.zip' -type f | sort -V)

        local _package="audio${_counter}.zip"

        zip -r $_package . -i *.mp3
        echo "ZIP generated '$_package' in: $YT_DLP_AUDIO_OUTPUT_FOLDER"

        read -p "Remove packed MP3 files? y/n> " _yesno
        case $_yesno in
            [Yy]*)
                find . -name '*.mp3' -type f -delete
                find . -type d -empty -delete
                echo "MP3 files were cleaned"
            ;;
        esac
    else
        echo "MP3 files not found in: $YT_DLP_AUDIO_OUTPUT_FOLDER"
    fi

    _completed
}

_move_outputs() {
    cd "$YT_DLP_AUDIO_OUTPUT_FOLDER"

    if [ -n "$(find . -name '*.zip')" ]; then
        rsync -av --remove-source-files $YT_DLP_AUDIO_OUTPUT_FOLDER/*.zip "$DOWNLOADS_HOME"
        echo "ZIP files moved to: $DOWNLOADS_HOME"
    else
        echo "ZIP files not found in: $YT_DLP_AUDIO_OUTPUT_FOLDER"
    fi

    _completed
}

_download_audio() {
    local _url=${1:-}
    local _source=${2:-}
    local _start_in=${3:--1}

    cd "$YT_DLP_AUDIO_OUTPUT_FOLDER/$_source"

    if [ $_start_in -gt 0 ]; then
        yt-dlp -x --audio-format mp3 --audio-quality 4 \
            --playlist-start $_start_in \
            --restrict-filenames --windows-filenames \
            --rm-cache-dir --no-overwrites \
            -o "%(uploader)s/%(title)s.%(ext)s" "$_url"
    else
        yt-dlp -x --audio-format mp3 --audio-quality 4 \
            --restrict-filenames --windows-filenames \
            --rm-cache-dir --no-overwrites \
            -o "%(uploader)s/%(title)s.%(ext)s" "$_url"
    fi

    if [ $? -eq 0 ]; then
        local _recent_file=$( fd -t f . -x stat -c "%y %n" {} \; | sort -r | head -1 )

        echo >&2
        echo "Downloaded: $_url" >&2
        echo "Output file: $_recent_file" >&2
    else
        echo >&2
        echo "Unable to download: $_url" >&2
    fi
}

_download_resource() {
    local _url=${1:-}
    local _list=${2:-}
    local _source=${3:-}
    local _start_in=${4:--1}

    if [ -z "$_list" ]; then
        _download_audio "$_url" $_start_in
    else
        while IFS= read -r line || [ -n "$line" ]; do
            _download_audio "$line"
        done < $_list

        echo ;
        cat $_list
        rm -f $_list
    fi
}

_playlist_start=-1
_src_url=""
_list_file=""
_source="YouTube"
_operation=""

while getopts "u:s:i:l:pmh" opt; do
    case "$opt" in
        u)
            _src_url="$OPTARG"
            ;;
        s)
            _source="$OPTARG"
            ;;
        i)
            _playlist_start=$OPTARG
            ;;
        l)
            _list_file="$OPTARG"
            ;;
        p)
            _operation=_pack_audios
            ;;
        m)
            _operation=_move_outputs
            ;;
        h)
            __usage_page
            ;;
    esac
done

if [ -n "$_operation" ]; then
    eval "$_operation $_source"

    _completed
fi

echo ;
echo "Tip: If URL has '&' params, remove if don't needed or use any of the alternatives:"
echo "  quote: $0 -u '...&<param>=<value>'"
echo "  escape: $0 -u ...\\&<param>=<value>"

_download_resource "$_src_url" "$_list_file" "$_source" $_playlist_start

_completed
