#! /usr/bin/env bash
BASEDIR=$(dirname $0); cd $BASEDIR

. ../.libs/env-vars

_require_var OUTPUT_AUDIO_HOME

__usage_page() {
    cat << EOF
Converts MP4 files to MP3.

Usage: $(basename $0) [<option>]*
Option:
    -i: Sets the MP4 location/file
    -o: Sets the MP3 output location. Default: 'OUTPUT_AUDIO_HOME'
    -h: Displays this help message
EOF
    exit 0
}

_convert() {
    local _mp4=${1:-}
    local _filename=$(basename -- "$_mp4")
    local _name="${_filename%.*}"
    local _output="$_mp3_output/$_name.mp3"

    echo >&2

    ffmpeg -y -loglevel warning -i "$_mp4" -vn -acodec libmp3lame -ac 2 -ab 160k -ar 48000 "$_output"

    echo "Input: $_mp4" >&2
    echo "Output: $_output" >&2
}

_mp4_location=""
_mp3_output="$OUTPUT_AUDIO_HOME"

while getopts "i:o:h" opt; do
    case "$opt" in
        i)
            _mp4_location="$OPTARG"
            ;;
        o)
            _mp3_output="$OPTARG"
            ;;
        h)
            __usage_page
            ;;
    esac
done

if [ -d "$_mp4_location" ]; then
    echo "Reading: $_mp4_location" >&2
    echo >&2

    for _mp4 in "$_mp4_location"/*.mp4 ; do
        _convert "$_mp4"
    done
elif [ -f "$_mp4_location" ]; then
    _convert "$_mp4_location"
else
    echo "Invalid MP4 location/file: $_mp4_location" >&2
    _stopped
fi

_completed
