#! /usr/bin/env bash
BASEDIR=$(dirname $0); cd $BASEDIR

. ../env-vars

_require_var OUTPUT_TRANSCRIPTS_HOME

__usage_page() {
    echo "Transcribe a resource."
    echo ;
    echo "Usage: $(basename $0) [<option>]*"
    echo "Option:"
    echo "    -i: Sets the resource: video or audio"
    echo "    -o: Sets the transcripts output location. Default: 'OUTPUT_TRANSCRIPTS_HOME'"
    echo "    -h: Displays this help message"
    exit 0
}

_transcribe() {
    local _resource=${1:-}
    local _filename=$( basename -- "$_resource" | cut -d . -f 1 )
    local _output=${2:-}
    local _output="$_output/$_filename"

    echo ;

    transcribe-anything "$_resource" --output_dir "$_output"

    echo "Resource: $_resource"
    echo "Output: $_output"
}

_resource=""
_output="$OUTPUT_TRANSCRIPTS_HOME"

while getopts "i:o:h" opt; do
    case "$opt" in
        i)
            _resource="$OPTARG"
            ;;
        o)
            _output="$OPTARG"
            ;;
        h)
            __usage_page
            ;;
    esac
done

if [ -f "$_resource" ]; then
    _transcribe "$_resource" "$_output"
else
    echo "Invalid resource: $_resource"
    _stopped
fi

_completed
