#! /usr/bin/env bash
BASEDIR=$(dirname $0); cd $BASEDIR

. ../.libs/funcs
. ../env-vars

_require_var POKEMON_SOLUS_HOME
_require_var GB_GBC_ROMS_HOME

_usage() {
    echo "Builds Pokémon Solus ROMs."
    echo ;
    echo "Usage: $0 [<option>]*"
    echo "Option:"
    echo "    -h: Displays this help message"
    exit 0
}

while getopts "h" opt; do
    case "$opt" in
        h)
            _usage
            ;;
    esac
done

cd "$POKEMON_SOLUS_HOME"

make

rsync -cavP --remove-source-files pokesolusred.gbc "$GB_GBC_ROMS_HOME/Pokemon Solus Red Version.gbc"
rsync -cavP --remove-source-files pokesolusgreen.gbc "$GB_GBC_ROMS_HOME/Pokemon Solus Green Version.gbc"
rsync -cavP --remove-source-files pokesolusblue.gbc "$GB_GBC_ROMS_HOME/Pokemon Solus Blue Version.gbc"
rsync -cavP --remove-source-files pokesolusblue_debug.gbc "$GB_GBC_ROMS_HOME/"

_back

echo "[Completed]: $0"

