#! /usr/bin/env bash
BASEDIR=$(dirname $0); cd $BASEDIR

. ../.libs/funcs
. ../env-vars

_require_var GAMES_HOME

_usage() {
    echo "Launches a game console."
    echo ;
    echo "Usage: $0 [<option>]*"
    echo "Option:"
    echo "    -h: Displays this help message"
    exit 0
}

while getopts "h" opt; do
    case "$opt" in
        h)
            _usage
            ;;
    esac
done

_launch_zelda64() {
    echo >&2
    echo "Launching 'Zelda 64: Recompiled'" >&2

    _require_var ZELDA64RECOMPILED_HOME
    _require_var ZELDA64RECOMPILED_SAVES_HOME
    _require_var ZELDA64RECOMPILED_BACKUP_HOME

    rsync -cvrP $ZELDA64RECOMPILED_BACKUP_HOME/ $ZELDA64RECOMPILED_SAVES_HOME/

    cd $ZELDA64RECOMPILED_HOME

    ./Zelda64Recompiled "$@"

    rsync -cvrP $ZELDA64RECOMPILED_SAVES_HOME/ $ZELDA64RECOMPILED_BACKUP_HOME/

    cd $GAMES_HOME
    ./save-snapshot "$ZELDA64RECOMPILED_BACKUP_HOME"
}

_launch_1964gepd() {
    echo >&2
    echo "Launching '1964 GEPD Edition'" >&2

    _require_var GEPD_1964_HOME
    _require_var GEPD_1964_SAVES_HOME
    _require_var GEPD_1964_BACKUP_HOME

    rsync -cvrP $GEPD_1964_BACKUP_HOME/ $GEPD_1964_SAVES_HOME/

    cd $GEPD_1964_HOME

    echo "Full screen mode press: 'Alt+Enter'" >&2
    echo "Enable/disable mouse press: '4'" >&2

    wine 1964.exe "$@"

    rsync -cvrP $GEPD_1964_SAVES_HOME/ $GEPD_1964_BACKUP_HOME/

    cd $GAMES_HOME
    ./save-snapshot "$GEPD_1964_BACKUP_HOME"
}

_launch_dolphin() {
    echo >&2
    echo "Launching 'Dolphin'" >&2

    _require_var DOLPHIN_HOME
    _require_var DOLPHIN_SAVES_HOME
    _require_var DOLPHIN_BACKUP_HOME

    rsync -cvrP $DOLPHIN_BACKUP_HOME/ $DOLPHIN_SAVES_HOME/

    flatpak run org.DolphinEmu.dolphin-emu "$@"

    rsync -cvrP $DOLPHIN_SAVES_HOME/ $DOLPHIN_BACKUP_HOME/

    cd $GAMES_HOME
    ./save-snapshot "$DOLPHIN_BACKUP_HOME"
}

_launch_mupen64plus() {
    echo >&2
    echo "Launching 'Mupen64Plus'" >&2

    . ./start-mupen64plus "$@"

    cd $GAMES_HOME
    ./save-snapshot "$N64_SAVES_HOME"
}

_launch_mgba() {
    echo >&2
    echo "Launching 'mGBA'" >&2

    _require_var MGBA_HOME
    _require_var MGBA_BACKUP_HOME

    flatpak run io.mgba.mGBA "$@"

    cd $GAMES_HOME
    ./save-snapshot "$MGBA_BACKUP_HOME"
}

_launch_snes9x() {
    echo >&2
    echo Launching 'Snes9x' >&2

    _require_var SNES9X_HOME
    _require_var SNES9X_BACKUP_HOME

    flatpak run com.snes9x.Snes9x "$@"

    cd $GAMES_HOME
    ./save-snapshot "$SNES9X_BACKUP_HOME"
}

echo "Select a console:"
echo "1) Zelda 64: Recompiled"
echo "2) 1964 GEPD Edition"
echo "3) GameCube/Wii [Dolphin]"
echo "4) Nintendo 64 [Mupen64Plus]"
echo "5) GBA/GBC/GB [mGBA]"
echo "6) SNES [Snes9x]"
read -p "console-index> " _console_index

case "$_console_index" in
    1)
        _launch_zelda64 "$@"
        ;;
    2)
        _launch_1964gepd "$@"
        ;;
    3)
        _launch_dolphin "$@"
        ;;
    4)
        _launch_mupen64plus "$@"
        ;;
    5)
        _launch_mgba "$@"
        ;;
    6)
        _launch_snes9x "$@"
        ;;
    *)
        echo "Invalid console index"
        echo "[Process stopped]: $0"
        exit 0
        ;;
esac

_back

echo "[Completed]: $0"