#! /usr/bin/env bash
BASEDIR=$(dirname $0); cd $BASEDIR

. ../.libs/funcs
. ../env-vars

_require_var GAMES_HOME

_usage() {
    echo "Launches a game console."
    echo ;
    echo "Usage: $0 [<option>]*"
    echo "Option:"
    echo "    -h: Displays this help message"
    exit 0
}

while getopts "h" opt; do
    case "$opt" in
        h)
            _usage
            ;;
    esac
done

_launch_zelda64() {
    echo >&2
    echo "Launching 'Zelda 64: Recompiled'" >&2

    _require_var ZELDA64RECOMPILED_HOME
    _require_var ZELDA64RECOMPILED_SAVES_HOME
    _require_var ZELDA64RECOMPILED_BACKUP_HOME

    rsync -cvrP $ZELDA64RECOMPILED_BACKUP_HOME/ $ZELDA64RECOMPILED_SAVES_HOME/

    cd $ZELDA64RECOMPILED_HOME

    ./Zelda64Recompiled "$@"

    rsync -cvrP $ZELDA64RECOMPILED_SAVES_HOME/ $ZELDA64RECOMPILED_BACKUP_HOME/

    cd $GAMES_HOME
    ./take-snapshot "$ZELDA64RECOMPILED_BACKUP_HOME" bin
}

_launch_perfectdark() {
    echo >&2
    echo "Launching 'perfect_dark'" >&2

    _require_var PERFECTDARK_HOME
    _require_var PERFECTDARK_ROM
    _require_var PERFECTDARK_SAVES_HOME
    _require_var PERFECTDARK_BACKUP_HOME

    rsync -cvrP $PERFECTDARK_BACKUP_HOME/ $PERFECTDARK_SAVES_HOME/

    cd $PERFECTDARK_HOME

    ./pd --rom-file "$PERFECTDARK_ROM" "$@"

    rsync -cvrPa $PERFECTDARK_SAVES_HOME/eeprom.bin $PERFECTDARK_BACKUP_HOME/

    cd $GAMES_HOME
    ./take-snapshot "$PERFECTDARK_BACKUP_HOME" bin
}

_launch_1964gepd() {
    echo >&2
    echo "Launching '1964 GEPD Edition'" >&2

    _require_var GEPD_1964_HOME
    _require_var GEPD_1964_SAVES_HOME
    _require_var GEPD_1964_BACKUP_HOME

    rsync -cvrP $GEPD_1964_BACKUP_HOME/ $GEPD_1964_SAVES_HOME/

    cd $GEPD_1964_HOME

    wine 1964.exe "$@"

    rsync -cvrP $GEPD_1964_SAVES_HOME/ $GEPD_1964_BACKUP_HOME/

    cd $GAMES_HOME
    ./take-snapshot "$GEPD_1964_BACKUP_HOME" eep
}

_launch_dolphin() {
    echo >&2
    echo "Launching 'Dolphin'" >&2

    flatpak run org.DolphinEmu.dolphin-emu "$@"

    cd $GAMES_HOME
    ./take-snapshot "$DOLPHIN_BACKUP_HOME" gci
}

_launch_mupen64plus() {
    echo >&2
    echo "Launching 'Mupen64Plus'" >&2

    _require_var N64_ROMS_HOME
    _require_var N64_SAVES_HOME
    _require_var GB_GBC_ROMS_HOME
    _require_var GB_GBC_SAVES_HOME
    _require_var N64_CONFIGURED_JOYSTICK_NAMES
    _require_var N64_CONFIGURED_JOYSTICK_CONFIGS
    _require_var N64_CONFIGURED_JOYSTICK_DEFAULT

    . ./n64-profiles
    . ./start-mupen64plus "$@"

    cd $GAMES_HOME
    ./take-snapshot "$N64_SAVES_HOME" eep mpk fla
}

_launch_mgba() {
    echo >&2
    echo "Launching 'mGBA'" >&2

    flatpak run io.mgba.mGBA "$@"

    cd $GAMES_HOME
    ./take-snapshot "$MGBA_BACKUP_HOME" sav ss1
}

_launch_snes9x() {
    echo >&2
    echo Launching 'Snes9x' >&2

    flatpak run com.snes9x.Snes9x "$@"

    cd $GAMES_HOME
    ./take-snapshot "$SNES9X_BACKUP_HOME" 000 0A.frz srm oops
}

echo "Select a console:"
echo "1) Zelda 64: Recompiled"
echo "2) 1964 GEPD Edition"
echo "3) GameCube/Wii"
echo "4) Nintendo 64"
echo "5) GBA/GBC/GB"
echo "6) SNES"
# echo "7) Perfect Dark port"
read -p "console-index> " _console_index

case "$_console_index" in
    1)
        _launch_zelda64 "$@"
        ;;
    2)
        _launch_1964gepd "$@"
        ;;
    3)
        _launch_dolphin "$@"
        ;;
    4)
        _launch_mupen64plus "$@"
        ;;
    5)
        _launch_mgba "$@"
        ;;
    6)
        _launch_snes9x "$@"
        ;;
    # 7)
    #     _launch_perfectdark "$@"
    #     ;;
    *)
        echo "Invalid console index"
        echo "[Process stopped]: $0"
        exit 0
        ;;
esac

_back

echo "[Completed]: $0"