#! /usr/bin/env bash
BASEDIR=$(dirname $0); cd $BASEDIR

. ../env-vars
require_var GEPD_1964_HOME
require_var GEPD_1964_SAVES_HOME
require_var GEPD_1964_BACKUP_HOME

rsync -cvrP $GEPD_1964_BACKUP_HOME $GEPD_1964_SAVES_HOME

cd $GEPD_1964_HOME

echo Launching '1964 GEPD Edition' at "$GEPD_1964_HOME"
wine 1964.exe

rsync -cvrP $GEPD_1964_SAVES_HOME $GEPD_1964_BACKUP_HOME

back
