#! /usr/bin/env bash
BASEDIR=$(dirname $0); cd $BASEDIR

. ../libs
. ../env-vars

_usage() {
    echo "Launches a game console."
    echo ;
    echo "Usage: $0 [<option>]*"
    echo "Option:"
    echo "    -h: Displays this help message"
    exit 0
}

while getopts "h" opt; do
    case "$opt" in
        h)
            _usage
            ;;
    esac
done

_consoles=(
    "zelda64|Zelda 64: Recompiled"
    "perfectdark|Perfect Dark port"
    "1964gepd|1964 GEPD Edition"
    "dolphin|GameCube/Wii"
    "mupen64plus|Nintendo 64"
    "mgba|GBA/GBC/GB"
    "snes9x|SNES"
)
echo "Select a console:"
for _idx in "${!_consoles[@]}"; do
    _console_opt=$( cut -d \| -f 2 <<< "${_consoles[$_idx]}" )

    echo "$((_idx+1))) $_console_opt"
done
read -p "console-index> " _console_index

if [ -z "$_console_index" ]; then
    echo "Invalid console index"
    echo "[Process stopped]"
    exit 0
fi

_emu=$( cut -d \| -f 1 <<< "${_consoles[$((_console_index-1))]}" )
_console_name=$( cut -d \| -f 2 <<< "${_consoles[$((_console_index-1))]}" )

if [ -z "$_emu" ]; then
    echo "Invalid console index"
    echo "[Process stopped]"
    exit 0
fi

_launch_zelda64() {
    _require_var ZELDA64RECOMPILED_HOME
    _require_var ZELDA64RECOMPILED_SAVES_HOME
    _require_var ZELDA64RECOMPILED_BACKUP_HOME

    rsync -cvrP $ZELDA64RECOMPILED_BACKUP_HOME $ZELDA64RECOMPILED_SAVES_HOME

    cd $ZELDA64RECOMPILED_HOME

    ./Zelda64Recompiled

    rsync -cvrP $ZELDA64RECOMPILED_SAVES_HOME $ZELDA64RECOMPILED_BACKUP_HOME
}

_launch_perfectdark() {
    _require_var PERFECTDARK_HOME
    _require_var PERFECTDARK_ROM
    _require_var PERFECTDARK_SAVES_HOME
    _require_var PERFECTDARK_BACKUP_HOME

    rsync -cvrP $PERFECTDARK_BACKUP_HOME $PERFECTDARK_SAVES_HOME

    cd $PERFECTDARK_HOME

    ./pd --rom-file "$PERFECTDARK_ROM"

    rsync -cvrPa $PERFECTDARK_SAVES_HOME/eeprom.bin $PERFECTDARK_BACKUP_HOME
}

_launch_1964gepd() {
    _require_var GEPD_1964_HOME
    _require_var GEPD_1964_SAVES_HOME
    _require_var GEPD_1964_BACKUP_HOME

    rsync -cvrP $GEPD_1964_BACKUP_HOME $GEPD_1964_SAVES_HOME

    cd $GEPD_1964_HOME

    wine 1964.exe

    rsync -cvrP $GEPD_1964_SAVES_HOME $GEPD_1964_BACKUP_HOME
}

_launch_dolphin() {
    flatpak run org.DolphinEmu.dolphin-emu
}

_launch_mupen64plus() {
    _require_var N64_ROMS_HOME
    _require_var N64_CONFIGURED_JOYSTICK_NAMES
    _require_var N64_CONFIGURED_JOYSTICK_CONFIGS
    _require_var N64_CONFIGURED_JOYSTICK_DEFAULT

    . ./n64-profiles
    . ./start-mupen64plus
}

_launch_mgba() {
    flatpak run io.mgba.mGBA
}

_launch_snes9x() {
    flatpak run com.snes9x.Snes9x
}

echo "Launching '$_console_name'"
eval "_launch_$_emu"

_back

echo "[Completed]"