@echo OFF

call env-vars.bat
call require-var ZELDA64RECOMPILED_HOME
call require-var ZELDA64RECOMPILED_SAVES_HOME
call require-var ZELDA64RECOMPILED_BACKUP_HOME

robocopy "%ZELDA64RECOMPILED_BACKUP_HOME%" "%ZELDA64RECOMPILED_SAVES_HOME%" /z

cd %ZELDA64RECOMPILED_HOME%

echo Launching 'Zelda 64: Recompiled' at "%ZELDA64RECOMPILED_HOME%"
Zelda64Recompiled.exe

robocopy "%ZELDA64RECOMPILED_SAVES_HOME%" "%ZELDA64RECOMPILED_BACKUP_HOME%" /z

take-snapshot "%ZELDA64RECOMPILED_BACKUP_HOME%" bin

cd %PWD%
