#! /usr/bin/env bash
BASEDIR=$(dirname $0); cd $BASEDIR

. ../.libs/funcs
. ../env-vars

_require_var SNAPSHOTS_TO_KEEP
_require_var SCRIPTS_LIBS_HOME

_usage() {
    echo "Create snapshots of save files."
    echo ;
    echo "Usage: $0 [<option>]*"
    echo "Option:"
    echo "    -h: Displays this help message"
    exit 0
}

while getopts "h" opt; do
    case "$opt" in
        h)
            _usage
            ;;
    esac
done

_saves_home="$1"

python "$SCRIPTS_LIBS_HOME/file-snapshot.py" "$_saves_home" $SNAPSHOTS_TO_KEEP

_back

echo ;
echo "[Completed]: $0"
