#! /usr/bin/env bash

_saves_home="$1"
_snapshots_home="${_saves_home}/snapshots"

if [ -n "$SNAPSHOTS_TO_KEEP" ]; then
    _number_to_keep=$SNAPSHOTS_TO_KEEP
else
    _number_to_keep=10
fi

_save_exts=()
_arg_idx=1

for _arg in "$@"; do
    if [ $_arg_idx -gt 1 ]; then
        _save_exts+=( "$_arg" )
    fi
    _arg_idx=$((_arg_idx+1))
done

_save_names=()

for _ext in "${_save_exts[@]}"; do
    for _save_file_name in "$_saves_home"/*.$_ext; do
        _save_name=$( basename "$_save_file_name" | cut -f 1 -d '.' )

        if ! [[ "${_save_names[@]}" =~ "$_save_name" ]] && ! [ "$_save_name" = "*" ]; then
            _save_names+=( "$_save_name" )
        fi
    done
done

if [ ${#_save_names[@]} -eq 0 ]; then
    echo "Snapshot not created"
    exit 0
fi

_default_save_file=$((${#_save_names[@]}+1))

echo "Choose a save file to create a snapshot:"
for _idx in "${!_save_names[@]}"; do
    _save_name="${_save_names[$_idx]}"

    echo "$((_idx+1))) $_save_name"
done

echo "$_default_save_file) (default) <skip snapshot>"

read -p "save-index> " _save_file_idx

if [ -z "$_save_file_idx" ]; then
    _save_file_idx=$_default_save_file
fi

_save_selected="${_save_names[$((_save_file_idx-1))]}"

if [ -z "$_save_selected" ]; then
    echo "Snapshot not created"
    exit 0
fi

if ! [ -d "$_snapshots_home" ]; then
    mkdir "$_snapshots_home"
fi

for _ext in "${_save_exts[@]}"; do
    _save_file="$_save_selected.$_ext"
    _snapshot_file="$_save_file.$(date +%Y%m%d-%H%M%S)"
    _save_file_path="$_saves_home/$_save_file"
    _snapshot_file_path="$_snapshots_home/$_snapshot_file"

    if [ -f "$_save_file_path" ]; then
        echo "Creating snapshot: '$_snapshot_file_path'"
        cp "$_save_file_path" "$_snapshot_file_path"

        (
            cd $_snapshots_home
            ls -tp | grep -i "$_save_file*" | tail -n +$((_number_to_keep+1)) | xargs -d "\n" -r rm --
        )
    fi
done
