#! /usr/bin/env bash
BASEDIR=$(dirname $0); cd $BASEDIR

. ./env-vars
require_var OUTPUT_AUDIO_FOLDER
require_var DOWNLOADS_HOME

rsync -av --remove-source-files $OUTPUT_AUDIO_FOLDER/*.zip "$DOWNLOADS_HOME"
