#! /usr/bin/env bash
BASEDIR=$(dirname $0); cd $BASEDIR

PWD=$(pwd)

__usage_page() {
    echo "Imports configuration from a cloud provider."
    echo ;
    echo "Usage: $(basename $0) [<option>]*"
    echo "Option:"
    echo "    -h: Displays this help message"
    exit 0
}

_append_env_vars() {
    local _env_vars="${1:-}/env-vars"
    if [ ! "$(grep -in "ENV_VARS_FILE=*" ~/.bashrc)" ]; then
        if [ -f "$_env_vars" ]; then
            echo 'env-vars' file found, adding environment variable to ~/.bashrc >&2
            echo "ENV_VARS_FILE=\"$_env_vars\"" >&2
            sed -i "$ a\\\nexport ENV_VARS_FILE=\"$_env_vars\"" ~/.bashrc
        fi
    fi
}

_yes_prompt() {
    echo "${1:-}" >&2
    echo "y) Yes (default)" >&2
    echo "n) No" >&2
    read -p "y/n> " _yesno
    if [ -z "$_yesno" ]; then
        _yesno=y
    fi
    echo "$_yesno"
}

_validate_dir() {
    local _dir=${1:-}
    if [ ! -d "$_dir" ]; then
        echo >&2
        echo "Directory does not exist: $_dir" >&2
        _yesno=$( _yes_prompt "Do you want to create it?" )
        case $_yesno in
            [Yy]*)
                mkdir -p "$_dir"
            ;;
            *)
                _stopped
            ;;
        esac
    fi
}

_trim_separator() {
    echo "${1:-}" | sed 's/^\/*\|\/*$//g'
}

_trim_trailing_separator() {
    echo "${1:-}" | sed 's/\/*$//'
}

while getopts "h" opt; do
    case "$opt" in
        h)
            __usage_page
            ;;
    esac
done

echo "Enter the cloud directory for:" >&2
echo >&2
echo "$( hostnamectl | grep 'Operating System:' )" >&2
read -p "cloud-directory> " CLOUD_DIRECTORY
eval "CLOUD_DIRECTORY=\$( _trim_trailing_separator \"$CLOUD_DIRECTORY\" )"

echo >&2
echo "Enter the rclone config:" >&2
read -p "rclone-config> " RCLONE_CONFIG

CLOUD_DIRECTORY="$CLOUD_DIRECTORY/$RCLONE_CONFIG"

_validate_dir "$CLOUD_DIRECTORY"

echo >&2
echo "Enter the backup directory for:" >&2
read -p 'backup-directory> ' BACKUP_DIRECTORY
eval "BACKUP_DIRECTORY=\$( _trim_separator \"$BACKUP_DIRECTORY\" )"

BACKUP_HOME=$CLOUD_DIRECTORY/$BACKUP_DIRECTORY

_validate_dir "$BACKUP_HOME"

if [ -z "$( ls -A $BACKUP_HOME )" ]; then
    rclone copy -P $RCLONE_CONFIG:$BACKUP_DIRECTORY $BACKUP_HOME

    echo >&2
    echo "Imported source: $RCLONE_CONFIG:$BACKUP_DIRECTORY" >&2
    echo "Destination: $BACKUP_HOME" >&2

    _append_env_vars "$BACKUP_HOME"
else
    rclone sync -P $RCLONE_CONFIG:$BACKUP_DIRECTORY $BACKUP_HOME

    echo >&2
    echo "Synchronized source: $RCLONE_CONFIG:$BACKUP_DIRECTORY" >&2
    echo "Destination: $BACKUP_HOME" >&2

    _append_env_vars "$BACKUP_HOME"
fi

echo >&2
echo "[Completed]: $0" >&2

cd $PWD
exit 0
