#! /usr/bin/env bash
BASEDIR=$(dirname $0); cd $BASEDIR

. ./.libs/funcs

_usage() {
    echo "Imports configuration from a cloud provider."
    echo ;
    echo "Usage: $0 [<option>]*"
    echo "Option:"
    echo "    -h: Displays this help message"
    exit 0
}

_append_env_vars() {
    local _env_vars="${1:-}/env-vars"
    if [ ! "$(grep -in "ENV_VARS_FILE=*" ~/.bashrc)" ]; then
        if [ -f "$_env_vars" ]; then
            echo 'env-vars' file found, adding environment variable to ~/.bashrc
            echo "ENV_VARS_FILE=\"$_env_vars\""
            sed -i "$ a\\\nexport ENV_VARS_FILE=\"$_env_vars\"" ~/.bashrc
        fi
    fi
}

while getopts "h" opt; do
    case "$opt" in
        h)
            _usage
            ;;
    esac
done

echo "Enter the cloud directory for:"
echo -e "\t$( hostnamectl | grep 'Operating System:' )"
read -p "cloud-directory> " CLOUD_DIRECTORY
eval "CLOUD_DIRECTORY=\$( _trim_trailing_separator \"$CLOUD_DIRECTORY\" )"

echo ;
echo "Enter the rclone config:"
read -p "rclone-config> " RCLONE_CONFIG

CLOUD_DIRECTORY="$CLOUD_DIRECTORY/$RCLONE_CONFIG"

_validate_dir "$CLOUD_DIRECTORY"

echo ;
echo "Enter the backup directory for:"
read -p 'backup-directory> ' BACKUP_DIRECTORY
eval "BACKUP_DIRECTORY=\$( _trim_separator \"$BACKUP_DIRECTORY\" )"

BACKUP_HOME=$CLOUD_DIRECTORY/$BACKUP_DIRECTORY

_validate_dir "$BACKUP_HOME"

if [ -z "$( ls -A $BACKUP_HOME )" ]; then
    rclone copy -P $RCLONE_CONFIG:$BACKUP_DIRECTORY $BACKUP_HOME

    echo ;
    echo "Imported source: $RCLONE_CONFIG:$BACKUP_DIRECTORY"
    echo "Destination: $BACKUP_HOME"

    _append_env_vars "$BACKUP_HOME"
else
    rclone sync -P $RCLONE_CONFIG:$BACKUP_DIRECTORY $BACKUP_HOME

    echo ;
    echo "Synchronized source: $RCLONE_CONFIG:$BACKUP_DIRECTORY"
    echo "Destination: $BACKUP_HOME"

    _append_env_vars "$BACKUP_HOME"
fi

_completed
