#! /usr/bin/env bash
BASEDIR=$(dirname $0); cd $BASEDIR

. ./libs
. ./env-vars

_require_var EXECS_HOME
_require_var EXECUTABLE_COMMANDS

_usage() {
    echo "Launches an AppImage file."
    echo ;
    echo "Usage: $0 [<option>]*"
    echo "Option:"
    echo "    -h: Displays this help message"
    exit 0
}

while getopts "h" opt; do
    case "$opt" in
        h)
            _usage
            ;;
    esac
done

if [ ! -d "$EXECS_HOME" ]; then
    echo "Directory not found: $EXECS_HOME"
    echo "[Process stopped]"
    exit 0
fi

_app_paths=( $( find "$EXECS_HOME" -type f -name "*.AppImage" ) )

for _bin in "${EXECUTABLE_COMMANDS[@]}"; do
    _app_paths+=( "$_bin" )
done

echo "Select an AppImage/Executable:"
for _idx in "${!_app_paths[@]}"; do
    _app_path="${_app_paths[$_idx]}"

    echo "$((_idx+1))) $( echo $_app_path | sed -r 's/^.+\///' )"
done
read -p "app-index> " _app_index

if [ -z "$_app_index" ]; then
    echo "Invalid app index"
    echo "[Process stopped]"
    exit 0
fi

_app_path="${_app_paths[$((_app_index-1))]}"

if [ -z "$_app_path" ]; then
    echo "Invalid app index"
    echo "[Process stopped]"
    exit 0
fi

cd $EXECS_HOME

$_app_path

_back

echo "[Completed]"