#! /usr/bin/env bash
BASEDIR=$(dirname $0); cd $BASEDIR

. ./libs
. ./env-vars

_require_var EXECS_HOME

_usage() {
    echo "Launches an AppImage file."
    echo ;
    echo "Usage: $0 [<option>]*"
    echo "Option:"
    echo "    -h: Displays this help message"
    exit 0
}

while getopts "h" opt; do
    case "$opt" in
        h)
            _usage
            ;;
    esac
done

if [ ! -d "$EXECS_HOME" ]; then
    echo "Directory not found: $EXECS_HOME"
    echo "[Process stopped]"
    exit 0
fi

_app_paths=($( find "$EXECS_HOME" -type f -name "*.AppImage" ))

if [[ -z ${_app_paths[@]} ]]; then
    echo "AppImage files not found in: $EXECS_HOME"
    echo "[Process stopped]"
    exit 0
fi

echo "Select an AppImage:"
for _idx in "${!_app_paths[@]}"; do
    _app_value="${_app_paths[$_idx]}"
    echo "$((_idx+1))) $( echo $_app_value | sed -r 's/^.+\///' )"
done
read -p "app-index> " _app_index

if [ -z "$_app_index" ]; then
    echo "Invalid console index"
    echo "[Process stopped]"
    exit 0
fi

_app_path="${_app_paths[$((_app_index-1))]}"

if [ -z "$_app_path" ]; then
    echo "Invalid console index"
    echo "[Process stopped]"
    exit 0
fi

$_app_path

_back

echo "[Completed]"