#! /usr/bin/env bash
BASEDIR=$(dirname $0); cd $BASEDIR

. ./libs
. ./env-vars

_require_var APP_IMAGES_HOMES

_usage() {
    echo "Launches an AppImage file."
    echo ;
    echo "Usage: $0 [<option>]*"
    echo "Option:"
    echo "    -h: Displays this help message"
    exit 0
}

while getopts "h" opt; do
    case "$opt" in
        h)
            _usage
            ;;
    esac
done

_app_homes=()

echo "Select an AppImage:"
for _idx in "${!APP_IMAGES_HOMES[@]}"; do
    _app_home_cmd="echo \$${APP_IMAGES_HOMES[$_idx]}"
    _app_home=$( eval $_app_home_cmd )
    _app_opt=$( ls $_app_home | grep ".*\.AppImage$" )
    echo "$((_idx+1))) $_app_opt"

    _app_homes+=("$_app_home")
done
read -p "app-index> " _app_index

_app_home="${_app_homes[$((_app_index-1))]}"

if [ -z "$_app_home" ]; then
    echo "Invalid console index"
    echo "[Process stopped]"
    exit 0
fi

cd $_app_home

./*.AppImage

_back

echo "[Completed]"