#! /usr/bin/env bash
BASEDIR=$(dirname $0); cd $BASEDIR

. ./env-vars
require_var CLOUD_HOME
require_var CLOUD_REMOTE_SOURCES

_cloud_home=$( trim_trailing_separator "$CLOUD_HOME" )

for _src in "${CLOUD_REMOTE_SOURCES[@]}"
do
    _config=$( cut -d : -f 1 <<< "$_src" ) 
    _path=$( cut -d : -f 2 <<< "$_src" )
    _path=$( trim_separator "$_path" )

    rclone copy -P $_config:$_path "$_cloud_home/$_config/$_path"
    rclone sync -P $_config:$_path "$_cloud_home/$_config/$_path"

    echo "[Pull completed]"
done
