#! /usr/bin/env bash
BASEDIR=$(dirname $0); cd $BASEDIR

. ./env-vars

_require_var WORKSPACE_HOME
_require_var UPDATE_PLAN_FILE

__usage_page() {
    echo "Update packages and execute a plan."
    echo ;
    echo "Usage: $0 [<option>]*"
    echo "Option:"
    echo "    -h: Displays this help message"
    exit 0
}

while getopts "h" opt; do
    case "$opt" in
        h)
            __usage_page
            ;;
    esac
done

echo "Updating packages:"
echo -e "$( hostnamectl | grep 'Operating System:' )"

if [ -n "$( type -t apt )" ]; then

    sudo -l 1>/dev/null
    if [ $? -ne 0 ] || ! [ "$( sudo whoami )" = "root" ]; then
        echo "Execute:"
        echo "> su \$USER"
        _stopped
    fi

    echo ;
    echo "Updating 'apt' packages"

    sudo apt update
    sudo apt upgrade -y

    echo "Cleaning up 'apt' packages"

    sudo apt clean all -y
    sudo apt autoclean -y
    sudo apt autoremove --purge -y
fi

if [ -n "$( type -t dnf )" ]; then
    echo ;
    echo "Updating 'dnf' packages"

    sudo dnf check-update
    sudo dnf upgrade -y
fi

_print_cmds=()

if [ -f "$UPDATE_PLAN_FILE" ]; then
    while IFS= read -r line || [ -n "$line" ]; do
        _cmd=$( echo "${line//[$'\t\r\n']}" )
        _exe=$( cut -d : -f 1 <<< "$_cmd" )

        if [ "$_exe" = "p" ]; then
            _cmd=$( echo "$_cmd" | cut -b 3- )
            _print_cmds+=( "$_cmd" )
        else
            echo ;
            echo "Executing: [$_cmd]"
            eval "$_cmd"
        fi
    done < $UPDATE_PLAN_FILE
fi

if [ ${#_print_cmds[*]} -gt 0 ]; then
    echo ;
    echo "Execute these update commands if needed:"

    for _cmd in "${_print_cmds[@]}"; do
        echo "> $_cmd"
    done
fi

_completed
