#! /usr/bin/env bash
BASEDIR=$(dirname $0); cd $BASEDIR

. ./env-vars

_require_var WORKSPACE_HOME
_require_var UPDATE_PLAN_FILE

__usage_page() {
    echo "Execute the update plan."
    echo ;
    echo "Usage: $(basename $0) [<option>]*"
    echo "Option:"
    echo "    -h: Displays this help message"
    exit 0
}

while getopts "h" opt; do
    case "$opt" in
        h)
            __usage_page
            ;;
    esac
done

uname -m && cat /etc/*release

echo ;
hostnamectl

if [ -n "$( type -t sudo )" ]; then
    sudo -l 1>/dev/null
    if [ $? -ne 0 ] || ! [ "$( sudo whoami )" = "root" ]; then
        echo "Execute:"
        echo "> su \$USER"
        _stopped
    fi
fi

_print_cmds=()

if [ -f "$UPDATE_PLAN_FILE" ]; then
    while IFS= read -r line || [ -n "$line" ]; do
        _cmd=$( echo "${line//[$'\t\r\n']}" )
        _exe=$( cut -d : -f 1 <<< "$_cmd" )

        if [ "$_exe" = "p" ]; then
            _cmd=$( echo "$_cmd" | cut -b 3- )
            _print_cmds+=( "$_cmd" )
        else
            echo ;
            echo "Executing: [$_cmd]"
            eval "$_cmd"
        fi
    done < $UPDATE_PLAN_FILE
fi

if [ ${#_print_cmds[*]} -gt 0 ]; then
    echo ;
    echo "Execute these update commands if needed:"

    for _cmd in "${_print_cmds[@]}"; do
        echo "> $_cmd"
    done
fi

_completed
