#! /usr/bin/env bash
BASEDIR=$(dirname $0); cd $BASEDIR

. ../env-vars

__usage_page() {
    echo "Creates directories based on 'env-vars' file."
    echo ;
    echo "Usage: $(basename $0) [<option>]*"
    echo "Option:"
    echo "    -h: Displays this help message"
    exit 0
}

while getopts "h" opt; do
    case "$opt" in
        h)
            __usage_page
            ;;
    esac
done

echo "Creating directories"

if [ -n "$EXECS_HOME" ]; then sudo mkdir -vp "$EXECS_HOME"; fi
if [ -n "$WORKSPACE_HOME" ]; then
    mkdir -vp "$WORKSPACE_HOME/github"
fi
if [ -n "$STORAGE_HOME" ]; then
    mkdir -vp "$STORAGE_HOME/dist"
    mkdir -vp "$STORAGE_HOME/iso"
    mkdir -vp "$STORAGE_HOME/llm"
    mkdir -vp "$STORAGE_HOME/devices"
fi
if [ -n "$CLOUD_HOME" ]; then mkdir -vp "$CLOUD_HOME"; fi
if [ -n "$REPOS_HOME" ]; then mkdir -vp "$REPOS_HOME"; fi
if [ -n "$MEDIA_HOME" ]; then
    mkdir -vp "$MEDIA_HOME/music"
fi
if [ -n "$YT_DLP_HOME" ]; then mkdir -vp "$YT_DLP_HOME"; fi
if [ -n "$YT_DLP_AUDIO_OUTPUT_FOLDER" ]; then mkdir -vp "$YT_DLP_AUDIO_OUTPUT_FOLDER"; fi
if [ -n "$YT_DLP_VIDEO_OUTPUT_FOLDER" ]; then mkdir -vp "$YT_DLP_VIDEO_OUTPUT_FOLDER"; fi
if [ -n "$ROMS_HOME" ]; then mkdir -vp "$ROMS_HOME"; fi
if [ -n "$OUTPUT_HOME" ]; then mkdir -vp "$OUTPUT_HOME"; fi
if [ -n "$OUTPUT_AUDIO_HOME" ]; then mkdir -vp "$OUTPUT_AUDIO_HOME"; fi
if [ -n "$OUTPUT_PARSED_HOME" ]; then mkdir -vp "$OUTPUT_PARSED_HOME"; fi
if [ -n "$OUTPUT_TRANSCRIPTION_HOME" ]; then mkdir -vp "$OUTPUT_TRANSCRIPTION_HOME"; fi
if [ -n "$OUTPUT_WEB_HOME" ]; then mkdir -vp "$OUTPUT_WEB_HOME"; fi

_completed
