#! /usr/bin/env bash
BASEDIR=$(dirname $0); cd $BASEDIR

. ../env-vars

# http://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html
: "${SNAPSHOTS_TO_KEEP:=1}"

__usage_page() {
    cat << EOF
Create snapshots of save files.

Usage: $(basename $0) [<option>]*
Option:
    -r: Recovers save from snapshots
    -h: Displays this help message
EOF
    exit 0
}

_recover_flag=0

while getopts "rh" opt; do
    case "$opt" in
        r)
            _recover_flag=1
            ;;
        h)
            __usage_page
            ;;
    esac
done

_saves_home="$1"

if ! [ $_recover_flag -eq 1 ]; then
    $(command -v python3 || command -v python) "./.py/file_snapshot.py" -d "$_saves_home" -k $SNAPSHOTS_TO_KEEP
else
    $(command -v python3 || command -v python) "./.py/file_snapshot.py" -d "$_saves_home" --recover
fi

_completed
