#! /usr/bin/env bash

. ../env-vars

_require_var SNAPSHOTS_TO_KEEP

__usage_page() {
    echo "Create snapshots of save files."
    echo ;
    echo "Usage: $0 [<option>]*"
    echo "Option:"
    echo "    -r: Recovers save from snapshots"
    echo "    -h: Displays this help message"
    exit 0
}

_recover_flag=0

while getopts "rh" opt; do
    case "$opt" in
        r)
            _recover_flag=1
            ;;
        h)
            __usage_page
            ;;
    esac
done

_saves_home="$1"

if ! [ $_recover_flag -eq 1 ]; then
    $(command -v python3 || command -v python) "./.py/file_snapshot.py" -d "$_saves_home"
else
    $(command -v python3 || command -v python) "./.py/file_snapshot.py" -d "$_saves_home" --recover
fi

_completed
