#! /usr/bin/env bash
BASEDIR=$(dirname $0); cd $BASEDIR

. ../env-vars

__usage_page() {
    echo "Pull changes for local repos or clone if they do not exist."
    echo ;
    echo "Usage: $0 [<option>]*"
    echo "Option:"
    echo "    -b: Backup repos as ZIP files"
    echo "    -s: Allow select a repo"
    echo "    -h: Displays this help message"
    exit 0
}

while getopts "bsh" opt; do
    case "$opt" in
        h)
            __usage_page
            ;;
        *)
            ;;
    esac
done

$(command -v python3 || command -v python) "./.py/backup_repos.py" $*

_completed