#! /usr/bin/env bash
BASEDIR=$(dirname $0); cd $BASEDIR

. ../.libs/env-vars

__usage_page() {
    cat << EOF
Pull changes for local repos or clone if they do not exist.

Usage: $(basename $0) [<option>]*
Option:
    -b: Backup repos as ZIP files
    -s: Allow select a repo
    -h: Displays this help message
EOF
    exit 0
}

while getopts "bsh" opt; do
    case "$opt" in
        h)
            __usage_page
            ;;
        *)
            ;;
    esac
done

$(command -v python3 || command -v python) "./.py/backup_repos.py" $*

_completed