#! /usr/bin/env bash
SOURCEDIR=$(pwd); BASEDIR=$(dirname $0); cd $BASEDIR

. $SCRIPTS_HOME/.libs/env-vars

_require_var SYS_CONTROL_DB_FILE
_require_var MACHINE_CONTROL_NAME
_require_var OS_CONTROL_NAME

__usage_page() {
    cat << EOF
Pull changes for local repos or clone if they do not exist.

Usage: $(basename $0) [<option>]*
Option:
    -b: Backup repos as ZIP files
    -s: Allow select a repo
    -h: Displays this help message
EOF
    exit 0
}

while getopts "bsh" opt; do
    case "$opt" in
        h)
            __usage_page
            ;;
        *)
            ;;
    esac
done

$(command -v python3 || command -v python) "$SCRIPTS_HOME/sys/.py/backup_repos.py" \
    -n "$MACHINE_CONTROL_NAME" -o "$OS_CONTROL_NAME" $*

_completed