#! /usr/bin/env bash
BASEDIR=$(dirname $0); cd $BASEDIR

. ../env-vars

__usage_page() {
    echo "Update 'dnf' packages."
    echo ;
    echo "Usage: $(basename $0) [<option>]*"
    echo "Option:"
    echo "    -h: Displays this help message"
    exit 0
}

_update() {
    if [ -n "$( type -t dnf )" ]; then
        echo ;
        echo "Updating 'dnf' packages"

        sudo dnf check-update
        sudo dnf upgrade -y
    fi
}

while getopts "h" opt; do
    case "$opt" in
        h)
            __usage_page
            ;;
        *)
            ;;
    esac
done

_update

_completed