#! /usr/bin/env bash
SOURCEDIR=$(pwd); BASEDIR=$(dirname $0); cd $BASEDIR

. ../.libs/env-vars

__usage_page() {
    cat << EOF
Update 'apt' and 'apt-get' packages.

Usage: $(basename $0) [<option>]*
Option:
    -c: Cleans up packages
    -h: Displays this help message
EOF
    exit 0
}

_update() {
    if [ -n "$( type -t apt )" ]; then
        echo >&2
        echo "Updating 'apt' packages" >&2

        sudo apt update
        sudo apt upgrade -y
    fi

    if [ -n "$( type -t apt-get )" ]; then
        echo >&2
        echo "Updating 'apt-get' packages" >&2

        sudo apt-get update
        sudo apt-get upgrade -y
    fi
}

_cleanup() {
    if [ -n "$( type -t apt )" ]; then
        echo "Cleaning up 'apt' packages" >&2

        sudo apt remove -y
        sudo apt clean -y
        sudo apt clean all -y
        sudo apt autoclean -y
        sudo apt autoremove --purge -y
    fi

    if [ -n "$( type -t apt-get )" ]; then
        echo >&2
        echo "Cleaning up 'apt-get' packages" >&2

        sudo apt-get clean -y
        sudo apt-get autoclean -y
        sudo apt-get autoremove -y
    fi
}

while getopts "ch" opt; do
    case "$opt" in
        c)
            _cleanup
            ;;
        h)
            __usage_page
            ;;
        *)
            ;;
    esac
done

_update

_completed