#! /usr/bin/env bash
BASEDIR=$(dirname $0); cd $BASEDIR

. ../env-vars

__usage_page() {
    echo "Update 'apt' and 'apt-get' packages."
    echo ;
    echo "Usage: $(basename $0) [<option>]*"
    echo "Option:"
    echo "    -c: Cleans up packages"
    echo "    -h: Displays this help message"
    exit 0
}

_update() {
    if [ -n "$( type -t apt )" ]; then
        echo ;
        echo "Updating 'apt' packages"

        sudo apt update
        sudo apt upgrade -y
    fi

    if [ -n "$( type -t apt-get )" ]; then
        echo ;
        echo "Updating 'apt-get' packages"

        sudo apt-get update
        sudo apt-get upgrade -y
    fi
}

_cleanup() {
    if [ -n "$( type -t apt )" ]; then
        echo "Cleaning up 'apt' packages"

        sudo apt remove -y
        sudo apt clean -y
        sudo apt clean all -y
        sudo apt autoclean -y
        sudo apt autoremove --purge -y
    fi

    if [ -n "$( type -t apt-get )" ]; then
        echo ;
        echo "Cleaning up 'apt-get' packages"

        sudo apt-get clean -y
        sudo apt-get autoclean -y
        sudo apt-get autoremove -y
    fi
}

while getopts "ch" opt; do
    case "$opt" in
        c)
            _cleanup
            ;;
        h)
            __usage_page
            ;;
        *)
            ;;
    esac
done

_update

_completed