#! /usr/bin/env bash
SOURCEDIR=$(pwd); BASEDIR=$(dirname $0); cd $BASEDIR

. ../.libs/env-vars

_require_var SYS_CONTROL_DB_FILE
_require_var MACHINE_CONTROL_NAME
_require_var OS_CONTROL_NAME
_require_var SCRIPTS_TEMP_DIR

__usage_page() {
    cat << EOF
Execute the update plan using bash.

Usage: $(basename $0) [<option>]*
Option:
    -a: Accept all commands
    -s: Start plan from specific command
    -o: Select and execute a command
    -h: Displays this help message
EOF
    exit 0
}

_accept=""
_mode="all"
while getopts "asoh" opt; do
    case "$opt" in
        a)
            _accept="--accept"
            ;;
        s)
            _mode='start-from'
            ;;
        o)
            _mode='only-one'
            ;;
        h)
            __usage_page
            ;;
    esac
done

_update_plan_tmp=$( mktemp "$SCRIPTS_TEMP_DIR/update-plan.bash.XXXXXXXXXX" )

echo >&2

$(command -v python3 || command -v python) "./.py/update_plan.py" -t bash \
    -n "$MACHINE_CONTROL_NAME" -o "$OS_CONTROL_NAME" \
    -f "$_update_plan_tmp" -m "$_mode" $_accept

. "$_update_plan_tmp"

rm -f "$_update_plan_tmp"

_completed
