#! /usr/bin/env bash
BASEDIR=$(dirname $0); cd $BASEDIR

. ../.libs/env-vars

__usage_page() {
    cat << EOF
Update 'dnf' packages.

Usage: $(basename $0) [<option>]*
Option:
    -h: Displays this help message
EOF
    exit 0
}

_update() {
    if [ -n "$( type -t dnf )" ]; then
        echo >&2
        echo "Updating 'dnf' packages" >&2

        sudo dnf check-update
        sudo dnf upgrade -y
    fi
}

while getopts "h" opt; do
    case "$opt" in
        h)
            __usage_page
            ;;
        *)
            ;;
    esac
done

_update

_completed