#! /usr/bin/env bash
BASEDIR=$(dirname $0); cd $BASEDIR

# Fetches all changes from backup folder (preferably a hosting service folder) to the pkb/org-roam/private

. ../env-vars
require_var SYNC_FOLDER_PRIVATE_DIR
require_var ORG_ROAM_PRIVATE_DIR

rsync -av "$SYNC_FOLDER_PRIVATE_DIR"/*.org "$ORG_ROAM_PRIVATE_DIR"

echo "Sync private pull completed"

