#! /usr/bin/env bash
BASEDIR=$(dirname $0); cd $BASEDIR

# Pushes all changes from pkb/org-roam/private directory to a backup folder (preferable a hosting service folder)

. ../env-vars
_require_var SYNC_FOLDER_PRIVATE_DIR
_require_var ORG_ROAM_PRIVATE_DIR

rsync -av "$ORG_ROAM_PRIVATE_DIR"/*.org "$SYNC_FOLDER_PRIVATE_DIR"

echo "Sync private push completed"

