#! /usr/bin/env bash
SOURCEDIR=$(pwd); BASEDIR=$(dirname $0); cd $BASEDIR

. $SCRIPTS_HOME/.libs/env-vars

_require_var OPENCODE_SERVER_PORT
_require_var GRAPHIFY_BACKEND
_require_var GRAPHIFY_MODEL

__usage_page() {
    cat << EOF
Starts OpenCode coding agent.

Usage: $(basename $0) [<option>]*
Option:
    -s: Starts OpenCode as server
    -i: [codebase-memory-mcp] Index project for AST
    -g: [Graphify] Setup and update project graph
    -h: Displays this help message
EOF
    exit 0
}

. $SCRIPTS_HOME/llm/.libs/agent-fn

_agent_graphify_file_ref="./.opencode/plugins/graphify.js"
_default_graphify_backend="$GRAPHIFY_BACKEND"
_default_graphify_model="$GRAPHIFY_MODEL"


_start_server() {
    _set_project

    echo "Starting OpenCode as server..." >&2
    echo >&2
    echo "> http://$WSL_IP:$OPENCODE_SERVER_PORT" >&2

    echo >&2
    opencode serve --port $OPENCODE_SERVER_PORT --hostname 0.0.0.0
}

_start_tui() {
    _set_project

    echo "Starting OpenCode as TUI..." >&2

    opencode
}

_server_flag=0

while getopts "sigh" opt; do
    case "$opt" in
        s)
            _server_flag=1
            ;;
        i)
            _setup_codebase_memory_mcp
            ;;
        g)
            _setup_graphify
            ;;
        h)
            __usage_page
            ;;
    esac
done

if [ $_server_flag -eq 1 ]; then
    _start_server
else
    _start_tui
fi

_completed
