#! /usr/bin/env bash
SOURCEDIR=$(pwd); BASEDIR=$(dirname $0); cd $BASEDIR

. $SCRIPTS_HOME/.libs/env-vars

_require_var GRAPHIFY_BACKEND
_require_var GRAPHIFY_MODEL

__usage_page() {
    cat << EOF
Initialize project and start a selected agent.

Usage: $(basename $0) [<option>]*
Option:
    -h: Displays this help message
EOF
    exit 0
}

_registered_agents=(
    "opencode"
    "pi"
)

_registered_plugins=(
    "Graphify"
    "CodeGraph"
)

_select_agent() {
    echo >&2
    echo "Select an agent:" >&2
    for _idx in "${!_registered_agents[@]}"; do
        _agent="${_registered_agents[$_idx]}"

        echo "$((_idx+1))) $_agent" >&2
    done
    read -p "agent-index> " _agent_idx

    if [ -z "$_agent_idx" ]; then
        echo "Invalid agent index" >&2
        _stopped
    fi

    _agent="${_registered_agents[$((_agent_idx-1))]}"

    if [ -z "$_agent" ]; then
        echo "Invalid agent index" >&2
        _stopped
    fi

    echo $_agent
}

_verify_graphify() {
    if [ -f "./.opencode/plugins/graphify.js" ]; then
        echo "Graphify"
    fi
}

_setup_graphify() {
    local _agent=${1:-}

    if [ -z "$( _verify_graphify )" ]; then
        echo >&2
        echo "Installing skill for agent '$_agent'" >&2
        graphify $_agent install --project

        echo "Initializing graph [backend=$GRAPHIFY_BACKEND model=$GRAPHIFY_MODEL]" >&2
        graphify . --backend "$GRAPHIFY_BACKEND" --model "$GRAPHIFY_MODEL"
    else
        echo >&2
        echo "Updating skill for agent '$_agent'" >&2
        graphify $_agent install

        echo "Updating graph [backend=$GRAPHIFY_BACKEND model=$GRAPHIFY_MODEL]" >&2
        graphify update . --backend "$GRAPHIFY_BACKEND" --model "$GRAPHIFY_MODEL"
    fi
}

_verify_codegraph() {
    if [ -d "./.codegraph" ]; then
        echo "CodeGraph"
    fi
}

_setup_codegraph() {
    local _agent=${1:-}

    if [ -z "$( _verify_codegraph )" ]; then
        echo >&2
        echo "Connecting to agent '$_agent'" >&2
        codegraph install --target $_agent --location local

        echo "Initializing index" >&2
        codegraph init -i
    else
        echo >&2
        codegraph status
    fi
}

_select_plugin() {
    echo >&2
    echo "Select a plugin:" >&2
    for _idx in "${!_registered_plugins[@]}"; do
        _plugin="${_registered_plugins[$_idx]}"

        echo "$((_idx+1))) $_plugin" >&2
    done
    read -p "plugin-index> " _plugin_idx

    if [ -z "$_plugin_idx" ]; then
        echo "Invalid plugin index" >&2
        _stopped
    fi

    _plugin="${_registered_plugins[$((_plugin_idx-1))]}"

    if [ -z "$_plugin" ]; then
        echo "Invalid plugin index" >&2
        _stopped
    fi

    echo $_plugin
}

_verify_plugin() {
    local _installed_plugins=()

    [ -n "$( _verify_graphify )" ] && _installed_plugins+=( "Graphify" )
    [ -n "$( _verify_codegraph )" ] && _installed_plugins+=( "CodeGraph" )

    if [[ ${#_installed_plugins[@]} -eq 1 ]]; then
        echo ${_installed_plugins[0]}
    else
        echo $( _select_plugin )
    fi
}

while getopts "h" opt; do
    case "$opt" in
        h)
            __usage_page
            ;;
    esac
done

echo >&2
echo "Project: $SOURCEDIR" >&2

cd "$SOURCEDIR"

_agent=$( _select_agent )
_plugin=$( _verify_plugin )

case $_plugin in
    Graphify)
        _setup_graphify $_agent
        ;;
    CodeGraph)
        _setup_codegraph $_agent
        ;;
    *)
        echo "Plugin not selected" >&2
        _stopped
        ;;
esac

case $_agent in
    opencode)
        opencode
        ;;
    pi)
        pi
        ;;
    *)
        echo "Agent not selected" >&2
        _stopped
        ;;
esac

_completed
