#! /usr/bin/env bash
BASEDIR=$(dirname $0); cd $BASEDIR

. ../.libs/funcs
. ../env-vars

_require_var OPEN_WEBUI_PORT
_require_var OPEN_WEBUI_WAIT_SECS
_require_var OPEN_WEBUI_WAIT_TRIES

# http://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html
: "${OPEN_WEBUI_TAG:=auto}"
: "${OPEN_WEBUI_OLLAMA_SERVER:=http://127.0.0.1:11434}"

_usage() {
    echo "Starts Ollama service and the Open WebUI."
    echo ;
    echo "Usage: $0 [<option>]*"
    echo "Option:"
    echo "    -o: Stop the current Open WebUI container"
    echo "    -r: Remove the current Open WebUI container"
    echo "    -h: Displays this help message"
    exit 0
}

_remove_container_by_tag() {
    local _tag=${1:-}

    if [ -n "$(docker ps -q -a -f name=open-webui-$_tag)" ]; then
        echo "Removing open-webui-$_tag ..."
        docker rm -f open-webui-$_tag
    else
        echo "Already removed open-webui-$_tag"
    fi
}

_remove_container() {
    if [[ "$OPEN_WEBUI_TAG" == auto* ]]; then
        _remove_container_by_tag "cuda"
        _remove_container_by_tag "main"
    else
        _remove_container_by_tag "$OPEN_WEBUI_TAG"
    fi
    
    _completed
}

_stop_container_by_tag() {
    local _tag=${1:-}

    if [ -n "$(docker ps -q -a -f name=open-webui-$_tag)" ]; then
        echo "Stopping open-webui-$_tag ..."
        docker container stop open-webui-$_tag
    else
        echo "Already stopped open-webui-$_tag"
    fi
}

_stop_container() {
    if [[ "$OPEN_WEBUI_TAG" == auto* ]]; then
        _stop_container_by_tag "cuda"
        _stop_container_by_tag "main"
    else
        _stop_container_by_tag "$OPEN_WEBUI_TAG"
    fi

    _completed
}

_start_container_by_tag() {
    local _tag=${1:-}
    local _gpu_opt=${2:-}

    if [ -z "$(docker ps -q -a -f name=open-webui-$_tag)" ]; then
        echo ;
        echo "Attempting to run open-webui-$_tag ..."

        docker run -d --network=host -e PORT="$OPEN_WEBUI_PORT" -e OLLAMA_BASE_URL="$OPEN_WEBUI_OLLAMA_SERVER" $_gpu_opt -v open-webui:/app/backend/data --name open-webui-$_tag ghcr.io/open-webui/open-webui:$_tag
    else
        echo ;
        echo "Attempting to restart open-webui-$_tag ..."

        docker container restart open-webui-$_tag
    fi
}

_update_container() {
    local _container=${1:-}

    echo ;
    echo "Attempting to update $_container ..."
    docker run --rm -v /var/run/docker.sock:/var/run/docker.sock nickfedor/watchtower --run-once $_container
}

_wait_until_up() {
    local _container=${1:-}
    local _container_id="$(docker ps -q -a -f name=$_container)"
    local _waiting_flag=0
    local _waited=0

    if ! [ "$(docker inspect --format='{{.State.Health.Status}}' $_container_id)" = "healthy" ]; then
        echo ;

        while [ $_waiting_flag -eq 0 ]; do
            echo "Waiting for $_container to run..."

            if ! [ "$(docker inspect --format='{{.State.Health.Status}}' $_container_id)" = "healthy" ]; then
                sleep $OPEN_WEBUI_WAIT_SECS
                let "_waited+=1"

                if [ $_waited -eq $OPEN_WEBUI_WAIT_TRIES ]; then
                    echo "Waited $(($OPEN_WEBUI_WAIT_SECS * $OPEN_WEBUI_WAIT_TRIES)) seconds, $_container is still not running."
                    exit 1
                fi
            else
                _waiting_flag=1
            fi
        done
    fi
}

while getopts "srh" opt; do
    case "$opt" in
        s)
            _stop_container
            ;;
        r)
            _remove_container
            ;;
        h)
            _usage
            ;;
    esac
done

if ! [ "$( systemctl is-active ollama )" = "active" ]; then
    ollama serve
fi

_recognized_container=""

if [[ "$OPEN_WEBUI_TAG" == auto* ]]; then
    _start_container_by_tag "cuda" "--gpus all"

    if ! [ $? -eq 0 ]; then
        echo ;
        echo "Unable to run open-webui-cuda"

        _start_container_by_tag "main"

        _recognized_container=open-webui-main
    else
        _recognized_container=open-webui-cuda
    fi
else
    _start_container_by_tag "$OPEN_WEBUI_TAG" "$OPEN_WEBUI_GPU_OPT"

    _recognized_container=open-webui-$OPEN_WEBUI_TAG
fi

_wait_until_up "$_recognized_container"

_update_container "$_recognized_container"

_wait_until_up "$_recognized_container"

echo ;
echo "> http://localhost:$OPEN_WEBUI_PORT"

_completed
