#! /usr/bin/env bash
BASEDIR=$(dirname $0); cd $BASEDIR

. ../env-vars

_require_var SCRIPTS_DEV_LIBS_HOME
_require_var OPEN_WEBUI_ENV
_require_var OPEN_WEBUI_PORT
_require_var OPEN_WEBUI_COMPOSE_FILE
_require_var OLLAMA_SERVER
_require_var DOCLING_SERVER
_require_var DOCLING_PORT
_require_var DOCKER_WAIT_SECS
_require_var DOCKER_WAIT_TRIES

_usage() {
    echo "Starts Ollama service, Open WebUI and Docling."
    echo ;
    echo "Usage: $0 [<option>]*"
    echo "Option:"
    echo "    -d: Start only Docling container"
    echo "    -t: Open the terminal for Open WebUI or Docling containers"
    echo "    -l: Show the logs for Open WebUI and Docling containers"
    echo "    -s: Stop Open WebUI and Docling containers"
    echo "    -r: Remove Open WebUI and Docling containers"
    echo "    -h: Displays this help message"
    exit 0
}

. "$SCRIPTS_DEV_LIBS_HOME/docker-fn"

_select_service() {
    _print "Which service do you want to connect?"
    _print "o) Open WebUI (default)"
    _print "d) Docling"
    read -p "o/d> " _service

    if [ -z "$_service" ]; then
        _service=o
    fi

    case "$_service" in
        o)
            echo "open-webui-$OPEN_WEBUI_ENV"
            ;;
        d)
            echo "docling-serve-$OPEN_WEBUI_ENV"
            ;;
        * )
            echo "Invalid service option: $_service"
            _stopped
            ;;
    esac
}

_start_ollama() {
    if ! [ "$( systemctl is-active ollama )" = "active" ]; then
        ollama serve
    fi
}

_docker_compose() {
    OPEN_WEBUI_PORT=$OPEN_WEBUI_PORT \
        OLLAMA_SERVER=$OLLAMA_SERVER \
        DOCLING_SERVER=$DOCLING_SERVER \
        DOCLING_PORT=$DOCLING_PORT \
        docker compose $*
}

_start_openwebui() {
    _start_ollama

    _docker_compose -f $OPEN_WEBUI_COMPOSE_FILE up

    _wait_until_healthy open-webui-$OPEN_WEBUI_ENV

    _update_container open-webui-$OPEN_WEBUI_ENV
    _update_container docling-serve-$OPEN_WEBUI_ENV

    _wait_until_healthy open-webui-$OPEN_WEBUI_ENV

    echo ;
    echo "> http://localhost:$OPEN_WEBUI_PORT"

    _completed
}

_terminal_openwebui() {
    _terminal_container $( _select_service )

    _completed
}

_logs_openwebui() {
    _docker_compose -f $OPEN_WEBUI_COMPOSE_FILE logs -f $( _select_service )

    _completed
}

_stop_openwebui() {
    _docker_compose -f $OPEN_WEBUI_COMPOSE_FILE stop

    _completed
}

_remove_openwebui() {
    _docker_compose -f $OPEN_WEBUI_COMPOSE_FILE down

    _completed
}

_start_docling() {
    _docker_compose -f $OPEN_WEBUI_COMPOSE_FILE run --rm docling-serve-$OPEN_WEBUI_ENV

    _update_container docling-serve-$OPEN_WEBUI_ENV

    _completed
}

while getopts "dtlsrh" opt; do
    case "$opt" in
        d)
            _start_docling
            ;;
        t)
            _terminal_openwebui
            ;;
        l)
            _logs_openwebui
            ;;
        s)
            _stop_openwebui
            ;;
        r)
            _remove_openwebui
            ;;
        h)
            _usage
            ;;
    esac
done

_start_openwebui
