#! /usr/bin/env bash
SOURCEDIR=$(pwd); BASEDIR=$(dirname $0); cd $BASEDIR

. $SCRIPTS_HOME/.libs/env-vars

_require_var GRAPHIFY_BACKEND
_require_var GRAPHIFY_MODEL

__usage_page() {
    cat << EOF
Starts Pi coding agent.

Usage: $(basename $0) [<option>]*
Option:
    -h: Displays this help message
EOF
    exit 0
}

. $SCRIPTS_HOME/llm/.libs/agent-fn


while getopts "h" opt; do
    case "$opt" in
        h)
            __usage_page
            ;;
    esac
done

echo >&2
echo "Project: $SOURCEDIR" >&2

cd "$SOURCEDIR"

_setup_plugin pi

pi

_completed
