#! /usr/bin/env bash
SOURCEDIR=$(pwd); BASEDIR=$(dirname $0); cd $BASEDIR

. $SCRIPTS_HOME/.libs/env-vars

_require_var OPENCODE_SERVER_PORT
_require_var GRAPHIFY_BACKEND
_require_var GRAPHIFY_MODEL

__usage_page() {
    cat << EOF
Starts OpenCode coding agent.

Usage: $(basename $0) [<option>]*
Option:
    -s: Starts OpenCode as server
    -p: Starts OpenCode with plugins
    -h: Displays this help message
EOF
    exit 0
}

. $SCRIPTS_HOME/llm/.libs/agent-fn


_start_server() {
    echo "Starting OpenCode as server..." >&2
    echo >&2
    echo "> http://$WSL_IP:$OPENCODE_SERVER_PORT" >&2

    echo >&2
    opencode serve --port $OPENCODE_SERVER_PORT --hostname 0.0.0.0
}

_start_tui() {
    echo "Starting OpenCode as TUI..." >&2

    opencode
}

_plugin_flag=0
_server_flag=0

while getopts "sh" opt; do
    case "$opt" in
        s)
            _server_flag=1
            ;;
        w)
            _plugin_flag=1
            ;;
        h)
            __usage_page
            ;;
    esac
done

echo >&2
echo "Project: $SOURCEDIR" >&2

cd "$SOURCEDIR"

if [ $_plugin_flag -eq 1 ]; then
    _setup_plugin opencode
fi

if [ $_server_flag -eq 1 ]; then
    _start_server
else
    _start_tui
fi

_completed
