#! /usr/bin/env bash
BASEDIR=$(dirname $0); cd $BASEDIR

. ../libs/funcs
. ../env-vars

_require_var OLLAMA_SERVER
_require_var OLLAMA_MODELS_DEF_FILE
_require_var OPENCODE_CONFIG_FILE
_require_var SCRIPTS_LLM_LIBS_HOME

_usage() {
    echo "Starts Ollama service and synchronizes models."
    echo ;
    echo "Usage: $0 [<option>]*"
    echo "Option:"
    echo "    -s: Syncs models with OpenCode configuration file"
    echo "    -h: Displays this help message"
    exit 0
}

_opencode_flag=0

while getopts "sh" opt; do
    case "$opt" in
        s)
            _opencode_flag=1
            ;;
        h)
            _usage
            ;;
    esac
done

if ! [ "$( systemctl is-active ollama )" = "active" ]; then
    ollama serve
fi

if ! [ $_opencode_flag -eq 1 ]; then
    python "$SCRIPTS_LLM_LIBS_HOME/pull-models.py" -o "$OLLAMA_SERVER" -m "$OLLAMA_MODELS_DEF_FILE"
else
    python "$SCRIPTS_LLM_LIBS_HOME/pull-models.py" -o "$OLLAMA_SERVER" -m "$OLLAMA_MODELS_DEF_FILE" -c $OPENCODE_CONFIG_FILE --sync
fi

_completed