#! /usr/bin/env bash
BASEDIR=$(dirname $0); cd $BASEDIR

. ../env-vars

_require_var OLLAMA_MODELS_DEF_FILE
_require_var OPENCODE_CONFIG_FILE

# http://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html
: "${OLLAMA_SERVER:=http://127.0.0.1:11434}"

__usage_page() {
    echo "Starts Ollama service, synchronizes models and updates OpenCode configuration."
    echo ;
    echo "Usage: $(basename $0) [<option>]*"
    echo "Option:"
    echo "    -s: Only syncs models on OpenCode configuration file"
    echo "    -h: Displays this help message"
    exit 0
}

_opencode_flag=0

while getopts "sh" opt; do
    case "$opt" in
        s)
            _opencode_flag=1
            ;;
        h)
            __usage_page
            ;;
    esac
done

if ! [ "$( systemctl is-active ollama )" = "active" ]; then
    ollama serve
fi

if ! [ $_opencode_flag -eq 1 ]; then
    $(command -v python3 || command -v python) "./.py/ollama_models.py" -a opencode
else
    $(command -v python3 || command -v python) "./.py/ollama_models.py" -a opencode --sync
fi

_completed