#! /usr/bin/env bash
BASEDIR=$(dirname $0); cd $BASEDIR

. ../env-vars

_require_var OLLAMA_SERVER
_require_var OLLAMA_MODELS_DEF_FILE
_require_var OPENCODE_CONFIG_FILE
_require_var PI_CONFIG_FILE

__usage_page() {
    echo "Starts Ollama service, synchronizes models and updates OpenCode/Pi configuration."
    echo ;
    echo "Usage: $(basename $0) [<option>]*"
    echo "Option:"
    echo "    -c: Only syncs models on OpenCode/Pi configuration file"
    echo "    -h: Displays this help message"
    exit 0
}

_sync_flag=0

while getopts "ch" opt; do
    case "$opt" in
        c)
            _sync_flag=1
            ;;
        h)
            __usage_page
            ;;
    esac
done

if ! [ "$( systemctl is-active ollama )" = "active" ]; then
    ollama serve
fi

if ! [ $_sync_flag -eq 1 ]; then
    $(command -v python3 || command -v python) "./.py/ollama_models.py" -a opencode -a pi
else
    $(command -v python3 || command -v python) "./.py/ollama_models.py" -a opencode -a pi --config
fi

_completed