#! /usr/bin/env bash

. ../env-vars

_require_var DOCKER_WAIT_SECS
_require_var DOCKER_WAIT_TRIES

_wait_until_healthy() {
    local _container=${1:-}
    local _container_id="$(docker ps -q -a -f name=$_container)"
    local _waiting_flag=0
    local _waited=0

    if ! [ "$(docker inspect --format='{{.State.Health.Status}}' $_container_id)" = "healthy" ]; then
        echo ;

        while [ $_waiting_flag -eq 0 ]; do
            echo "Waiting for $_container to run..."

            if ! [ "$(docker inspect --format='{{.State.Health.Status}}' $_container_id)" = "healthy" ]; then
                sleep $DOCKER_WAIT_SECS
                let "_waited+=1"

                if [ $_waited -eq $DOCKER_WAIT_TRIES ]; then
                    echo "Waited $(($DOCKER_WAIT_SECS * $DOCKER_WAIT_TRIES)) seconds, $_container is still not running."
                    exit 1
                fi
            else
                _waiting_flag=1
            fi
        done
    fi
}

_update_container() {
    local _container=${1:-}

    if [ -n "$(docker ps -q -a -f name=$_container)" ]; then
        echo "Attempting to update $_container ..."
        docker run --rm -v /var/run/docker.sock:/var/run/docker.sock nickfedor/watchtower --run-once $_container
    else
        echo "Container not found $_container"
    fi
}

_restart_container() {
    local _container=${1:-}

    if [ -n "$(docker ps -q -a -f name=$_container)" ]; then
        echo "Attempting to restart  $_container ..."
        docker container restart $_container
    else
        echo "Container not found $_container"
    fi
}

_stop_container() {
    local _container=${1:-}

    if [ -n "$(docker ps -q -a -f name=$_container)" ]; then
        echo "Stopping $_container ..."
        docker container stop $_container
    else
        echo "Container not found $_container"
    fi
}

_remove_container() {
    local _container=${1:-}

    if [ -n "$(docker ps -q -a -f name=$_container)" ]; then
        echo "Removing $_container ..."
        docker rm -f $_container
    else
        echo "Container not found $_container"
    fi
}

_terminal_container() {
    local _container=${1:-}

    if [ -n "$(docker ps -q -a -f name=$_container)" ]; then
        echo "Entering $_container ..."
        docker exec -it $_container /bin/bash
    else
        echo "Container not found $_container"
    fi
}
