#! /usr/bin/env bash
BASEDIR=$(dirname $0); cd $BASEDIR

. ../env-vars

_require_var REDIS_PORT

__usage_page() {
    echo "Starts Redis server."
    echo ;
    echo "Usage: $(basename $0) [<option>]*"
    echo "Option:"
    echo "    -s: Stop Redis server"
    echo "    -h: Displays this help message"
    exit 0
}

_stop() {
    _kill_process redis

    _completed
}

while getopts "sh" opt; do
    case "$opt" in
        s)
            _stop
            ;;
        h)
            __usage_page
            ;;
    esac
done

echo "Starting Redis server..."
sudo sysctl vm.overcommit_memory=1

redis-server --port $REDIS_PORT --daemonize yes

_completed
