#! /usr/bin/env bash
SOURCEDIR=$(pwd); BASEDIR=$(dirname $0); cd $BASEDIR

. $SCRIPTS_HOME/.libs/env-vars

_require_var REDIS_PORT

__usage_page() {
    cat << EOF
Starts Redis server.

Usage: $(basename $0) [<option>]*
Option:
    -s: Stop Redis server
    -h: Displays this help message
EOF
    exit 0
}

_stop() {
    _kill_process redis

    _completed
}

while getopts "sh" opt; do
    case "$opt" in
        s)
            _stop
            ;;
        h)
            __usage_page
            ;;
    esac
done

echo "Starting Redis server..." >&2
sudo sysctl vm.overcommit_memory=1

redis-server --port $REDIS_PORT --daemonize yes

_completed
