#! /usr/bin/env bash

# __usage_lib_page:
# Lists a Gcloud projects and allow to select one.
# It exports the following environment variables:
#   - PROJECT_SELECTED
#   - PUSH_PORT_SELECTED
#
# Usage in script:
#   . ./.libs/select-project  # Relative source

echo ;
echo "Select a project:"

for _idx in "${!GCLOUD_PROJECT_IDS[@]}"; do
    _project="${GCLOUD_PROJECT_IDS[$_idx]}"
    _name=$( cut -d : -f 1 <<< "$_project" )
    _id=$( cut -d : -f 2 <<< "$_project" )

    if [ "$GCLOUD_DEFAULT_PROJECT_ID" = "$((_idx+1))" ]; then
        echo "$((_idx+1))) (default) $_name [$_id]" >&2
    else
        echo "$((_idx+1))) $_name [$_id]" >&2
    fi
done

_project_index=""
_project_selected=""

read -p "project-index> " _project_index

if [ -z "$_project_index" ]; then
    _project_index=$GCLOUD_DEFAULT_PROJECT_ID
fi

if [ -n "$_project_index" ]; then
    _project_selected="${GCLOUD_PROJECT_IDS[$((_project_index-1))]}"
fi

if [ -z "$_project_selected" ]; then
    echo "Invalid project index"
    exit 1
else
    _project_id_selected=$( cut -d : -f 2 <<< "$_project_selected" )
    _push_port_selected=$( cut -d : -f 3 <<< "$_project_selected" )
fi

export PROJECT_SELECTED=$_project_id_selected
export PUSH_PORT_SELECTED=$_push_port_selected
