#! /usr/bin/env bash
BASEDIR=$(dirname $0); cd $BASEDIR

. ./.libs/env-vars

# Last assigned: 5
_require_var EMACS_WAIT_SECS

__usage_page() {
    cat << EOF
Starts Emacs editor.

Usage: $(basename $0) [<option>]*
Option:
    -t: Emacs Client Terminal
    -h: Displays this help message
EOF
    exit 0
}

_terminal_flag=0

while getopts "th" opt; do
    case "$opt" in
        t)
            _terminal_flag=1
            ;;
        h)
            __usage_page
            ;;
    esac
done

_emacs_pid=$( pidof -x emacs )

if [ -z "$_emacs_pid" ]; then
    echo "Launching 'Emacs Server'" >&2
    emacs --daemon &
    sleep $EMACS_WAIT_SECS
else
    echo "'Emacs Server' running at: $_emacs_pid" >&2
fi

_emacsclient_pid=$( pidof -x  emacsclient )

if [ -z "$_emacsclient_pid" ]; then
    if [ $_terminal_flag -eq 1 ]; then
        echo "Launching 'Emacs Client Terminal'" >&2
        emacsclient -t
    else
        echo "Launching 'Emacs Client'" >&2
        emacsclient -c -a 'emacs'
    fi
else
    echo "'Emacs Client' running at: $_emacsclient_pid" >&2
fi

_completed
