#! /usr/bin/env bash

# __usage_lib_page:
# Defines common agent functions
#
# Usage in script:
#   . $SCRIPTS_HOME/llm/.libs/agent-fn
#   SOURCEDIR=<source_directory>                   # Set to change source directory
#   _agent_graphify_file_ref=<graphify_file_ref>   # Set to change Graphify file ref
#   _default_graphify_backend=<graphify_backend>   # Set to change Graphify backend
#   _default_graphify_model=<graphify_model>       # Set to change Graphify model

: "${SOURCEDIR:=$(pwd)}"
: "${_agent_graphify_file_ref:=}"
: "${_default_graphify_backend:=openai}"
: "${_default_graphify_model:=}"

_set_project() {
    echo >&2
    echo "Project: $SOURCEDIR" >&2

    cd "$SOURCEDIR"
}

_setup_graphify() {
    _set_project

    if ! [ -f "$_agent_graphify_file_ref" ]; then
        echo >&2
        _init_flag=""
        read -p "Initialize Graphify? [y/n] > " _init_flag
        case $_init_flag in
            [Yy])
                echo >&2
                echo "[Graphify] Installing skill" >&2
                graphify $_agent install --project >&2
                ;;
            *)
                echo "Declined Graphify initialization" >&2
                ;;
        esac
    else
        echo >&2
        echo "[Graphify] Updating skill" >&2
        graphify $_agent install --project >&2
    fi

    if [ -f "$_agent_graphify_file_ref" ]; then
        if ! [ -f "./graphify-out/graph.json" ]; then
            echo >&2
            echo "[Graphify] Initializing graph ..." >&2
            echo "[backend=$_default_graphify_backend model=$_default_graphify_model]" >&2
            graphify . --backend $_default_graphify_backend --model $_default_graphify_model >&2
        else
            echo >&2
            _update_flag=""
            read -p "Re-extract changed files? [y/n] > " _update_flag
            case $_update_flag in
                [Yy])
                    echo "[Graphify] Updating graph - extracting changed files (this might take a few minutes) ..." >&2
                    echo "[backend=$_default_graphify_backend model=$_default_graphify_model]" >&2
                    graphify . --update --backend $_default_graphify_backend --model $_default_graphify_model >&2
                    ;;
                *)
                    echo "[Graphify] Updating graph - extracting code files (AST-only) ..." >&2
                    graphify update . >&2
                    ;;
            esac
        fi
    fi
}

_setup_codebase_memory_mcp() {
    _set_project

    echo >&2
    echo "[codebase-memory-mcp] Indexing project ..." >&2
    codebase-memory-mcp cli index_repository --repo-path "$SOURCEDIR" --mode full

    echo >&2
    echo "[codebase-memory-mcp] Exploring project architecture ..." >&2
    local _project=$( codebase-memory-mcp cli list_projects | jq -r ".projects[] | select(.root_path == \"$SOURCEDIR\") | .name" )
    codebase-memory-mcp cli get_architecture --project "$_project"
}
