#! /usr/bin/env bash
BASEDIR=$(dirname $0); cd $BASEDIR

. ./env-vars

# Last assigned: $WORKSPACE_HOME/github/private-gpt
_require_var PRIVATE_GPT_HOME

__usage_page() {
    cat << EOF
Starts LLM Server.

Usage: $(basename $0) [<option>]*
Option:
    -h: Displays this help message
EOF
    exit 0
}

while getopts "h" opt; do
    case "$opt" in
        h)
            __usage_page
            ;;
    esac
done

if ! [ "$( systemctl is-active ollama )" = "active" ]; then
    ollama serve
fi

cd $PRIVATE_GPT_HOME

PGPT_PROFILES=ollama make run
