# https://alexpasmantier.github.io/television/reference/channel-spec/
# https://alexpasmantier.github.io/television/community/channels-unix

[metadata]
name = "scripts"
description = "Browse and preview scripts"
requirements = [ "xclip", "fd", "rg" ]

[source]
command = [ "fd . \"$SCRIPTS_HOME\" | xargs rg '__usage_page\\(\\)' -l" ]
display = "{split:/:-1}"

[preview]
command = "'{}' -h"

[keybindings]
ctrl-e = "actions:execute"
ctrl-y = "actions:copy"

[actions.execute]
description = "Execute the selected script"
command = "'{}'"
mode = "execute"

[actions.copy]
description = "Copy the selected script"
command = "echo -n '{}' | xclip -sel clip"
mode = "execute"
