#! /usr/bin/env bash

# __usage_lib_page:
# Gets source and cookies host from a URL
#
# Dependencies:
#   - env-vars # Imported as source file
# Usage in script:
#   . ./.libs/url-source  # Relative source
#   _hosts_db_file=<hosts_db_file>  # Set hosts database file

: "${_hosts_db_file:=}"

_check_db() {
    if ! [ -f "$_hosts_db_file" ]; then
        echo "Database file not found, define it by setting '_hosts_db_file'" >&2
        _stopped
    fi
}

_get_source() {
    _check_db

    local _url=${1:-}
    local _host=$( echo "$_url" | awk -F/ '{print $3}' )
    local _query="SELECT source FROM url_mappings WHERE host='$_host';"
    local _result=$( sqlite3 "$_hosts_db_file" "$_query" )

    if [ -z "$_result" ]; then
        echo "Source not found for: $_host" >&2
        _stopped
    else
        echo "$_result"
    fi
}

_get_cookies_host() {
    _check_db

    local _url=${1:-}
    local _host=$( echo "$_url" | awk -F/ '{print $3}' )
    local _query="SELECT cookies_host FROM url_mappings WHERE host='$_host';"
    local _result=$( sqlite3 "$_hosts_db_file" "$_query" )

    if [ -z "$_result" ]; then
        echo "Cookies host not found for: $_host" >&2
        _stopped
    else
        echo "$_result"
    fi
}

_log_download() {
    _check_db

    local _url=${1:-}
    local _format=${2:-}
    local _status=${3:-}
    local _details=${4:-}
    local _output=${5:-}
    local _host=$( echo "$_url" | awk -F/ '{print $3}' )

    [ $_status -eq 0 ] && _status="'SUCCESS'" || _status="'FAILED'"
    [ -z "$_details" ] && _details="null" || _details="'$_details'"
    [ -z "$_output" ] && _output="null" || _output="'$_output'"

    local _query="SELECT id FROM downloads WHERE url = '$_url'"
    local _id=$( sqlite3 "$_hosts_db_file" "$_query" )

    if [ -n "$_id" ]; then
        local _update=" UPDATE downloads "
        _update+=" SET tries = tries + 1, "
        _update+=" format = '$_format', "
        _update+=" details = $_details, "
        _update+=" output_file = $_output, "
        _update+=" last_dl_status = $_status, "
        _update+=" last_dl_ts = CURRENT_TIMESTAMP "
        _update+=" WHERE id = '$_id'; "

        sqlite3 "$_hosts_db_file" "$_update"

        [ $? -eq 0 ] && echo "Updated '$_url': success ($?)" >&2 || echo "Updated '$_url': error ($?)"
    else
        local _insert=" INSERT INTO downloads(url, host, format, details, output_file, last_dl_status) "
        _insert+=" VALUES( "
        _insert+="'$_url', '$_host', '$_format', $_details, $_output, $_status"
        _insert+=" ); "

        sqlite3 "$_hosts_db_file" "$_insert"

        [ $? -eq 0 ] && echo "Inserted '$_url': success ($?)" >&2 || echo "Inserted '$_url': error ($?)"
    fi
}
