#! /usr/bin/env bash

# __usage_lib_page:
# Gets source and cookies host from a URL
#
# Usage in script:
#   . $SCRIPTS_HOME/misc/.libs/url-source  # Relative source
#   _url_source_db_file=<url_source_db_file>  # Set hosts database file

: "${_url_source_db_file:=}"

_check_db() {
    if ! [ -f "$_url_source_db_file" ]; then
        echo "Database file not found, define it by setting '_url_source_db_file'" >&2
        exit 1
    fi
}

_get_host_id() {
    _check_db

    local _url=${1:-}
    local _host=$( echo "$_url" | awk -F/ '{print $3}' )

    local _query=$( cat << EOF
    SELECT id
        FROM host_mappings
        WHERE host='$_host'
            AND deleted = 0
EOF
    )

    local _result=$( sqlite3 "$_url_source_db_file" "$_query" )

    if [ -z "$_result" ]; then
        echo "Id not found for: $_host" >&2
        exit 1
    else
        echo "$_result"
    fi
}

_get_source() {
    _check_db

    local _url=${1:-}
    local _host=$( echo "$_url" | awk -F/ '{print $3}' )

    local _query=$( cat << EOF
    SELECT source
        FROM host_mappings
        WHERE host='$_host'
            AND deleted = 0
EOF
    )

    local _result=$( sqlite3 "$_url_source_db_file" "$_query" )

    if [ -z "$_result" ]; then
        echo "Source not found for: $_host" >&2
        exit 1
    else
        echo "$_result"
    fi
}

_get_cookies_host() {
    _check_db

    local _url=${1:-}
    local _host=$( echo "$_url" | awk -F/ '{print $3}' )

    local _query=$( cat << EOF
    SELECT cookies_host
        FROM host_mappings
        WHERE host='$_host'
            AND deleted = 0
EOF
    )

    local _result=$( sqlite3 "$_url_source_db_file" "$_query" )

    if [ -z "$_result" ]; then
        echo "Cookies host not found for: $_host" >&2
        exit 1
    else
        echo "$_result"
    fi
}

_execute_cmd() {
    local _sentence=${1:-}
    local _details=${2:-}
    local _cmd="${_sentence,,}"

    [ -z "$_details" ] && _details="" || _details="($_details)"

    case "$_cmd" in 
        *insert*)
            _cmd=Insert
            ;;
        *update*)
            _cmd=Update
            ;;
        *delete*)
            _cmd=Delete
            ;;
        *)
            echo "Invalid command definition: '$_sentence'" >&2
            exit 1
            ;;
    esac

    sqlite3 "$_url_source_db_file" "$_sentence"

    local _exit=$?

    if [ $_exit -eq 0 ]; then
        echo "$_cmd $_details: db=success($_exit)" >&2
    else
        echo "$_cmd $_details: db=error($_exit)" >&2
    fi
}

_log_download() {
    _check_db

    local _url=${1:-}
    local _format=${2:-}
    local _status=${3:-}
    local _details=${4:-}
    local _output=${5:-}
    local _host_id=$( _get_host_id "$_url" )

    [ $_status -eq 0 ] && _status="'SUCCESS'" || _status="'FAILED'"
    [ -z "$_details" ] && _details="null" || _details="'$_details'"
    [ -z "$_output" ] && _output="null" || _output="'$_output'"

    local _cmd_msg="format=$_format, status=$_status, details=$_details, output=$_output"

    local _query=$( cat << EOF
    SELECT id
        FROM downloads
        WHERE url = '$_url'
            AND deleted = 0
EOF
    )

    local _id=$( sqlite3 "$_url_source_db_file" "$_query" )

    if [ -n "$_id" ]; then
        local _update=$( cat << EOF
        UPDATE downloads SET
                tries = tries + 1,
                format = '$_format',
                details = $_details,
                output_file = $_output,
                last_dl_status = $_status,
                last_dl_ts = CURRENT_TIMESTAMP
            WHERE id = '$_id';
EOF
        )

        _execute_cmd "$_update" "$_cmd_msg"
    else
        local _insert=$( cat << EOF
        INSERT INTO downloads(url, host_id, format, details, output_file, last_dl_status)
            VALUES('$_url', '$_host_id', '$_format', $_details, $_output, $_status);
EOF
        )

        _execute_cmd "$_insert" "$_cmd_msg"
    fi
}
