#! /usr/bin/env bash
SOURCEDIR=$(pwd); BASEDIR=$(dirname $0); cd $BASEDIR

. $SCRIPTS_HOME/.libs/env-vars

_require_var REPOS_DEF_FILE

__usage_page() {
    cat << EOF
Synchronize local repos.

Usage: $(basename $0) [<option>]*
Option:
    -h: Displays this help message
EOF
    exit 0
}

while getopts "h" opt; do
    case "$opt" in
        h)
            __usage_page
            ;;
    esac
done

_print_repos=()

if [ -n "$( type -t git )" ] && [ -f "$REPOS_DEF_FILE" ]; then
    while IFS= read -r line || [ -n "$line" ]; do
        _repo=$( eval echo "${line//[$'\t\r\n']}" )
        _exe=$( cut -d : -f 1 <<< "$_repo" )

        if [ "$_exe" = "p" ]; then
            _branch=$( cut -d : -f 2 <<< "$_repo" )
            _location=$( cut -d : -f 4 <<< "$_repo" )
            _print_repos+=( "[$_branch] $_location" )
        else
            _branch=$( cut -d : -f 1 <<< "$_repo" )
            _username=$( cut -d : -f 2 <<< "$_repo" )
            _location=$( cut -d : -f 3 <<< "$_repo" )
            _repo_name="$(basename $_location)"

            if ! [ -d "$_location" ]; then
                mkdir -vp "$_location"
                cd "$_location"
                cd ..
                rm -r "$_repo_name"

                echo >&2
                echo "Cloning $_repo_name ..." >&2

                git clone https://$_username/$_repo_name.git

                continue
            fi

            if [ -h "$_location" ]; then
                echo >&2
                echo "'$_location' is a symlink" >&2
                continue
            fi

            cd "$_location"

            echo >&2
            echo "Updating $_repo_name ..." >&2

            git checkout $_branch
            git pull origin $_branch
        fi
    done < $REPOS_DEF_FILE
fi

if [ ${#_print_repos[*]} -gt 0 ]; then
    echo >&2
    echo "Update these repos if needed:" >&2

    for _repo in "${_print_repos[@]}"; do
        echo "> $_repo"
    done
fi

_completed
