#! /usr/bin/env bash
BASEDIR=$(dirname $0); cd $BASEDIR

. ../.libs/env-vars

_require_var SYNC_FOLDER_PRIVATE_DIR
# Last assigned: $WORKSPACE_HOME/pkb/org-roam/private
_require_var ORG_ROAM_PRIVATE_DIR

__usage_page() {
    cat << EOF
Fetches all changes from backup folder (preferably a
hosting service folder) to the pkb/org-roam/private

Usage: $(basename $0) [<option>]*
Option:
    -h: Displays this help message
EOF
    exit 0
}

_push_flag=0

while getopts "h" opt; do
    case "$opt" in
        h)
            __usage_page
            ;;
    esac
done

_sync_ops=( "Pull" "Push" )

echo "Select an operation:" >&2
for _idx in "${!_sync_ops[@]}"; do
    _op="${_sync_ops[$_idx]}"

    echo "$((_idx+1))) $_op" >&2
done
read -p "operation-index> " _op_index

if [ -z "$_op_index" ]; then
    echo "Invalid operation index" >&2
    _stopped
fi

_sync_op="${_sync_ops[$((_op_index-1))]}"

if [ "$_sync_op" = "Push" ]; then
    _push_flag=1
fi

if [ $_push_flag -eq 1 ]; then
    echo "Pushing changes to '$SYNC_FOLDER_PRIVATE_DIR'" >&2
    rsync -av "$ORG_ROAM_PRIVATE_DIR"/*.org "$SYNC_FOLDER_PRIVATE_DIR"
else
    echo "Pulling changes from '$SYNC_FOLDER_PRIVATE_DIR'" >&2
    rsync -av "$SYNC_FOLDER_PRIVATE_DIR"/*.org "$ORG_ROAM_PRIVATE_DIR"
fi

_completed
