# https://alexpasmantier.github.io/television/reference/channel-spec/
# https://alexpasmantier.github.io/television/community/channels-windows

[metadata]
name = "scripts"
description = "Browse and preview scripts"
requirements = [ "clip", "fd", "rg" ]

[source]
command = [ "cmd /c \"$env:SCRIPTS_HOME\\.win\\list-files\" \"$env:SCRIPTS_HOME\" __usage_page bat" ]
display = "{split:\\\\:-1}"

[preview]
command = "cmd /c '{}' -h"

[keybindings]
ctrl-e = "actions:execute"
ctrl-y = "actions:copy"

[actions.execute]
description = "Execute the selected script"
command = "cmd /c '{}'"
mode = "execute"

[actions.copy]
description = "Copy the selected script"
command = "cmd /c echo '{}' | clip"
mode = "execute"
