#! /usr/bin/env bash

. ../.libs/funcs
. ../env-vars

_require_var SNAPSHOTS_TO_KEEP
_require_var SCRIPTS_LIBS_HOME

_usage() {
    echo "Create snapshots of save files."
    echo ;
    echo "Usage: $0 [<option>]*"
    echo "Option:"
    echo "    -r: Recovers save from snapshots"
    echo "    -h: Displays this help message"
    exit 0
}

_recover_flag=""

while getopts "rh" opt; do
    case "$opt" in
        r)
            _recover_flag=" --recover"
            ;;
        h)
            _usage
            ;;
    esac
done

_saves_home="$1"

python "$SCRIPTS_LIBS_HOME/file-snapshot.py" -d "$_saves_home"$_recover_flag

_completed
