#! /usr/bin/env bash

. ../libs/funcs
. ../env-vars

_require_var SNAPSHOTS_TO_KEEP
_require_var SCRIPTS_LIBS_HOME

_usage() {
    echo "Create snapshots of save files."
    echo ;
    echo "Usage: $0 [<option>]*"
    echo "Option:"
    echo "    -r: Recovers save from snapshots"
    echo "    -h: Displays this help message"
    exit 0
}

_recover_flag=0

while getopts "rh" opt; do
    case "$opt" in
        r)
            _recover_flag=1
            ;;
        h)
            _usage
            ;;
    esac
done

_saves_home="$1"

if ! [ $_recover_flag -eq 1 ]; then
    python "$SCRIPTS_LIBS_HOME/file-snapshot.py" -k "$SNAPSHOTS_TO_KEEP" -d "$_saves_home"
else
    python "$SCRIPTS_LIBS_HOME/file-snapshot.py" -k "$SNAPSHOTS_TO_KEEP" -d "$_saves_home" --recover
fi

_completed
