#! /usr/bin/env bash
BASEDIR=$(dirname $0); cd $BASEDIR

. ./env-vars

_require_var REPOS_DEF_FILE

_usage() {
    echo "Synchronize local repos."
    echo ;
    echo "Usage: $0 [<option>]*"
    echo "Option:"
    echo "    -h: Displays this help message"
    exit 0
}

while getopts "h" opt; do
    case "$opt" in
        h)
            _usage
            ;;
    esac
done

_print_repos=()

if [ -n "$( type -t git )" ] && [ -f "$REPOS_DEF_FILE" ]; then
    while IFS= read -r line || [ -n "$line" ]; do
        _repo=$( eval echo "${line//[$'\t\r\n']}" )
        _exe=$( cut -d : -f 1 <<< "$_repo" )

        if [ "$_exe" = "p" ]; then
            _branch=$( cut -d : -f 2 <<< "$_repo" )
            _location=$( cut -d : -f 4 <<< "$_repo" )
            _print_repos+=( "[$_branch] $_location" )
        else
            _branch=$( cut -d : -f 1 <<< "$_repo" )
            _username=$( cut -d : -f 2 <<< "$_repo" )
            _location=$( cut -d : -f 3 <<< "$_repo" )
            _repo_name="$(basename $_location)"

            if ! [ -d "$_location" ]; then
                mkdir -vp "$_location"
                cd "$_location"
                cd ..
                rm -r "$_repo_name"

                echo ;
                echo "Cloning $_repo_name ..."

                git clone https://$_username/$_repo_name.git

                continue
            fi

            if [ -h "$_location" ]; then
                echo ;
                echo "'$_location' is a symlink"
                continue
            fi

            cd "$_location"

            echo ;
            echo "Updating $_repo_name ..."

            git checkout $_branch
            git pull origin $_branch
        fi
    done < $REPOS_DEF_FILE
fi

if [ ${#_print_repos[*]} -gt 0 ]; then
    echo ;
    echo "Update these repos if needed:"

    for _repo in "${_print_repos[@]}"; do
        echo "> $_repo"
    done
fi

_completed
