#! /usr/bin/env bash
BASEDIR=$(dirname $0); cd $BASEDIR

. ./env-vars

# Last assigned: $WORKSPACE_HOME/github/private-gpt
_require_var PRIVATE_GPT_HOME

__usage_page() {
    echo "Starts LLM Server."
    echo ;
    echo "Usage: $0 [<option>]*"
    echo "Option:"
    echo "    -h: Displays this help message"
    exit 0
}

while getopts "h" opt; do
    case "$opt" in
        h)
            __usage_page
            ;;
    esac
done

if ! [ "$( systemctl is-active ollama )" = "active" ]; then
    ollama serve
fi

cd $PRIVATE_GPT_HOME

PGPT_PROFILES=ollama make run
