#! /usr/bin/env bash
BASEDIR=$(dirname $0); cd $BASEDIR

. ../env-vars

_require_var SYNC_FOLDER_PRIVATE_DIR
# Last assigned: $WORKSPACE_HOME/pkb/org-roam/private
_require_var ORG_ROAM_PRIVATE_DIR

__usage_page() {
    echo "Fetches all changes from backup folder (preferably a"
    echo "hosting service folder) to the pkb/org-roam/private"
    echo ;
    echo "Usage: $0 [<option>]*"
    echo "Option:"
    echo "    -h: Displays this help message"
    exit 0
}

_push_flag=0

while getopts "h" opt; do
    case "$opt" in
        h)
            __usage_page
            ;;
    esac
done

_sync_ops=( "Pull" "Push" )

echo "Select an operation:"
for _idx in "${!_sync_ops[@]}"; do
    _op="${_sync_ops[$_idx]}"

    echo "$((_idx+1))) $_op"
done
read -p "operation-index> " _op_index

if [ -z "$_op_index" ]; then
    echo "Invalid operation index"
    _stopped
fi

_sync_op="${_sync_ops[$((_op_index-1))]}"

if [ "$_sync_op" = "Push" ]; then
    _push_flag=1
fi

if [ $_push_flag -eq 1 ]; then
    echo "Pushing changes to '$SYNC_FOLDER_PRIVATE_DIR'"
    rsync -av "$ORG_ROAM_PRIVATE_DIR"/*.org "$SYNC_FOLDER_PRIVATE_DIR"
else
    echo "Pulling changes from '$SYNC_FOLDER_PRIVATE_DIR'"
    rsync -av "$SYNC_FOLDER_PRIVATE_DIR"/*.org "$ORG_ROAM_PRIVATE_DIR"
fi

_completed
