#! /usr/bin/env bash
BASEDIR=$(dirname $0); cd $BASEDIR

. ../.libs/funcs
. ../env-vars

# Last assigned: 0.0.0.0:9010
_require_var SPANNER_HOST_PORT

_usage() {
    echo "Starts Spanner emulator for a specific project."
    echo ;
    echo "Usage: $0 [<option>]*"
    echo "Option:"
    echo "    -h: Displays this help message"
    exit 0
}

while getopts "h" opt; do
    case "$opt" in
        h)
            _usage
            ;;
    esac
done

. ./select-project

_require_var PROJECT_SELECTED

gcloud emulators spanner start --host-port=$SPANNER_HOST_PORT &
sleep 2

SPANNER_ENVS=$TEMP_DIR/spanner/spanner-envs
SPANNER_TMP_HOME="$(dirname $SPANNER_ENVS)"

mkdir -vp "$SPANNER_TMP_HOME"

gcloud emulators spanner env-init > $SPANNER_ENVS

echo "export SPANNER_PROJECT_ID=$PROJECT_SELECTED" >> $SPANNER_ENVS
echo ;
echo "source $SPANNER_ENVS"

_completed