#! /usr/bin/env bash
BASEDIR=$(dirname $0); cd $BASEDIR

. ../env-vars

# Last assigned: 0.0.0.0:9010
_require_var SPANNER_HOST_PORT
_require_var GCLOUD_DEFAULT_PROJECT_ID
# Last assigned:
# GCLOUD_PROJECT_IDS=()
# GCLOUD_PROJECT_IDS+=( "project_name:project_id:project_port" )
#   project_name: Project name
#   project_id: Project ID
#   project_port: PubSub push endpoint port (e.g. 3000)
_require_var GCLOUD_PROJECT_IDS

__usage_page() {
    echo "Starts Spanner emulator for a specific project."
    echo ;
    echo "Usage: $(basename $0) [<option>]*"
    echo "Option:"
    echo "    -h: Displays this help message"
    exit 0
}

while getopts "h" opt; do
    case "$opt" in
        h)
            __usage_page
            ;;
    esac
done

. ./.libs/select-project

_require_var PROJECT_SELECTED

gcloud emulators spanner start --host-port=$SPANNER_HOST_PORT &
sleep 2

SPANNER_ENVS=$TEMP_DIR/spanner/spanner-envs
SPANNER_TMP_HOME="$(dirname $SPANNER_ENVS)"

mkdir -vp "$SPANNER_TMP_HOME"

gcloud emulators spanner env-init > $SPANNER_ENVS

echo "export SPANNER_PROJECT_ID=$PROJECT_SELECTED" >> $SPANNER_ENVS
echo ;
echo "source $SPANNER_ENVS"

_completed